#This is used by the top-level build.xml version target
#It is copied to version.properties
ramadda.version.date=2026-05-25 09:39 UTC
ramadda.version.major=26
ramadda.version.minor=9
ramadda.version.patch=0
ramadda.version=26.9.0

