#This is used by the top-level build.xml version target
#It is copied to version.properties
ramadda.version.date=2026-07-19 09:03 UTC
ramadda.version.major=26
ramadda.version.minor=51
ramadda.version.patch=0
ramadda.version=26.51.0

