#This is used by the top-level build.xml version target
#It is copied to version.properties
ramadda.version.date=2026-04-06 18:30 UTC
ramadda.version.major=25
ramadda.version.minor=62
ramadda.version.patch=0
ramadda.version=25.62.0

