#This file is generated by RAMADDA 

# Define a function to process the URLs
read_ramadda_data <- function(dest_dir = ".") {
# Define the list of URLs and corresponding file names
url_file_pairs <- list(
  ${urls}	       
)

  # Ensure the destination directory exists
  if (!dir.exists(dest_dir)) {
    dir.create(dest_dir, recursive = TRUE)
  }
  
  # Initialize a list to hold the data
  data_list <- list()
  
  # Iterate through the URL-file pairs
  for (pair in url_file_pairs) {
    url <- pair$url
    file_name <- pair$name
    file_path <- file.path(dest_dir, file_name)
    
    # Check if the file already exists
    if (!file.exists(file_path)) {
      tryCatch(
        {
          download.file(url, destfile = file_path, mode = "wb")
        },
        error = function(e) {
          cat("Failed to download:", url, "\n")
        }
      )
    } else {
      cat("File already exists:", file_name, "\n")
    }
    
    # Read the file into a data frame
    if (file.exists(file_path)) {
      cat("Reading file:", file_name, "\n")
      data <- tryCatch(
        {
          read.csv(file_path)
        },
        error = function(e) {
          cat("Failed to read:", file_name, "\n")
          NULL
        }
      )
      
      # Add the data frame to the list
      if (!is.null(data)) {
        data_list[[file_name]] <- data
      }
    }
  }
  
  return(data_list)
}

data_list <- download_and_read_files(url_file_pairs)


