convert activity.svg -fuzz 50% -transparent white activity.png
convert airplay.svg -fuzz 50% -transparent white airplay.png
convert alert-circle.svg -fuzz 50% -transparent white alert-circle.png
convert alert-octagon.svg -fuzz 50% -transparent white alert-octagon.png
convert alert-triangle.svg -fuzz 50% -transparent white alert-triangle.png
convert align-center.svg -fuzz 50% -transparent white align-center.png
convert align-justify.svg -fuzz 50% -transparent white align-justify.png
convert align-left.svg -fuzz 50% -transparent white align-left.png
convert align-right.svg -fuzz 50% -transparent white align-right.png
convert anchor.svg -fuzz 50% -transparent white anchor.png
convert aperture.svg -fuzz 50% -transparent white aperture.png
convert archive.svg -fuzz 50% -transparent white archive.png
convert arrow-down-circle.svg -fuzz 50% -transparent white arrow-down-circle.png
convert arrow-down-left.svg -fuzz 50% -transparent white arrow-down-left.png
convert arrow-down-right.svg -fuzz 50% -transparent white arrow-down-right.png
convert arrow-down.svg -fuzz 50% -transparent white arrow-down.png
convert arrow-left-circle.svg -fuzz 50% -transparent white arrow-left-circle.png
convert arrow-left.svg -fuzz 50% -transparent white arrow-left.png
convert arrow-right-circle.svg -fuzz 50% -transparent white arrow-right-circle.png
convert arrow-right.svg -fuzz 50% -transparent white arrow-right.png
convert arrow-up-circle.svg -fuzz 50% -transparent white arrow-up-circle.png
convert arrow-up-left.svg -fuzz 50% -transparent white arrow-up-left.png
convert arrow-up-right.svg -fuzz 50% -transparent white arrow-up-right.png
convert arrow-up.svg -fuzz 50% -transparent white arrow-up.png
convert at-sign.svg -fuzz 50% -transparent white at-sign.png
convert award.svg -fuzz 50% -transparent white award.png
convert bar-chart-2.svg -fuzz 50% -transparent white bar-chart-2.png
convert bar-chart.svg -fuzz 50% -transparent white bar-chart.png
convert battery-charging.svg -fuzz 50% -transparent white battery-charging.png
convert battery.svg -fuzz 50% -transparent white battery.png
convert bell-off.svg -fuzz 50% -transparent white bell-off.png
convert bell.svg -fuzz 50% -transparent white bell.png
convert bluetooth.svg -fuzz 50% -transparent white bluetooth.png
convert bold.svg -fuzz 50% -transparent white bold.png
convert book-open.svg -fuzz 50% -transparent white book-open.png
convert book.svg -fuzz 50% -transparent white book.png
convert bookmark.svg -fuzz 50% -transparent white bookmark.png
convert box.svg -fuzz 50% -transparent white box.png
convert briefcase.svg -fuzz 50% -transparent white briefcase.png
convert calendar.svg -fuzz 50% -transparent white calendar.png
convert camera-off.svg -fuzz 50% -transparent white camera-off.png
convert camera.svg -fuzz 50% -transparent white camera.png
convert cast.svg -fuzz 50% -transparent white cast.png
convert check-circle.svg -fuzz 50% -transparent white check-circle.png
convert check-square.svg -fuzz 50% -transparent white check-square.png
convert check.svg -fuzz 50% -transparent white check.png
convert chevron-down.svg -fuzz 50% -transparent white chevron-down.png
convert chevron-left.svg -fuzz 50% -transparent white chevron-left.png
convert chevron-right.svg -fuzz 50% -transparent white chevron-right.png
convert chevron-up.svg -fuzz 50% -transparent white chevron-up.png
convert chevrons-down.svg -fuzz 50% -transparent white chevrons-down.png
convert chevrons-left.svg -fuzz 50% -transparent white chevrons-left.png
convert chevrons-right.svg -fuzz 50% -transparent white chevrons-right.png
convert chevrons-up.svg -fuzz 50% -transparent white chevrons-up.png
convert chrome.svg -fuzz 50% -transparent white chrome.png
convert circle.svg -fuzz 50% -transparent white circle.png
convert clipboard.svg -fuzz 50% -transparent white clipboard.png
convert clock.svg -fuzz 50% -transparent white clock.png
convert cloud-drizzle.svg -fuzz 50% -transparent white cloud-drizzle.png
convert cloud-lightning.svg -fuzz 50% -transparent white cloud-lightning.png
convert cloud-off.svg -fuzz 50% -transparent white cloud-off.png
convert cloud-rain.svg -fuzz 50% -transparent white cloud-rain.png
convert cloud-snow.svg -fuzz 50% -transparent white cloud-snow.png
convert cloud.svg -fuzz 50% -transparent white cloud.png
convert code.svg -fuzz 50% -transparent white code.png
convert codepen.svg -fuzz 50% -transparent white codepen.png
convert codesandbox.svg -fuzz 50% -transparent white codesandbox.png
convert coffee.svg -fuzz 50% -transparent white coffee.png
convert columns.svg -fuzz 50% -transparent white columns.png
convert command.svg -fuzz 50% -transparent white command.png
convert compass.svg -fuzz 50% -transparent white compass.png
convert copy.svg -fuzz 50% -transparent white copy.png
convert corner-down-left.svg -fuzz 50% -transparent white corner-down-left.png
convert corner-down-right.svg -fuzz 50% -transparent white corner-down-right.png
convert corner-left-down.svg -fuzz 50% -transparent white corner-left-down.png
convert corner-left-up.svg -fuzz 50% -transparent white corner-left-up.png
convert corner-right-down.svg -fuzz 50% -transparent white corner-right-down.png
convert corner-right-up.svg -fuzz 50% -transparent white corner-right-up.png
convert corner-up-left.svg -fuzz 50% -transparent white corner-up-left.png
convert corner-up-right.svg -fuzz 50% -transparent white corner-up-right.png
convert cpu.svg -fuzz 50% -transparent white cpu.png
convert credit-card.svg -fuzz 50% -transparent white credit-card.png
convert crop.svg -fuzz 50% -transparent white crop.png
convert crosshair.svg -fuzz 50% -transparent white crosshair.png
convert database.svg -fuzz 50% -transparent white database.png
convert delete.svg -fuzz 50% -transparent white delete.png
convert disc.svg -fuzz 50% -transparent white disc.png
convert divide-circle.svg -fuzz 50% -transparent white divide-circle.png
convert divide-square.svg -fuzz 50% -transparent white divide-square.png
convert divide.svg -fuzz 50% -transparent white divide.png
convert dollar-sign.svg -fuzz 50% -transparent white dollar-sign.png
convert download-cloud.svg -fuzz 50% -transparent white download-cloud.png
convert download.svg -fuzz 50% -transparent white download.png
convert dribbble.svg -fuzz 50% -transparent white dribbble.png
convert droplet.svg -fuzz 50% -transparent white droplet.png
convert edit-2.svg -fuzz 50% -transparent white edit-2.png
convert edit-3.svg -fuzz 50% -transparent white edit-3.png
convert edit.svg -fuzz 50% -transparent white edit.png
convert external-link.svg -fuzz 50% -transparent white external-link.png
convert eye-off.svg -fuzz 50% -transparent white eye-off.png
convert eye.svg -fuzz 50% -transparent white eye.png
convert facebook.svg -fuzz 50% -transparent white facebook.png
convert fast-forward.svg -fuzz 50% -transparent white fast-forward.png
convert feather.svg -fuzz 50% -transparent white feather.png
convert figma.svg -fuzz 50% -transparent white figma.png
convert file-minus.svg -fuzz 50% -transparent white file-minus.png
convert file-plus.svg -fuzz 50% -transparent white file-plus.png
convert file-text.svg -fuzz 50% -transparent white file-text.png
convert file.svg -fuzz 50% -transparent white file.png
convert film.svg -fuzz 50% -transparent white film.png
convert filter.svg -fuzz 50% -transparent white filter.png
convert flag.svg -fuzz 50% -transparent white flag.png
convert folder-minus.svg -fuzz 50% -transparent white folder-minus.png
convert folder-plus.svg -fuzz 50% -transparent white folder-plus.png
convert folder.svg -fuzz 50% -transparent white folder.png
convert framer.svg -fuzz 50% -transparent white framer.png
convert frown.svg -fuzz 50% -transparent white frown.png
convert gift.svg -fuzz 50% -transparent white gift.png
convert git-branch.svg -fuzz 50% -transparent white git-branch.png
convert git-commit.svg -fuzz 50% -transparent white git-commit.png
convert git-merge.svg -fuzz 50% -transparent white git-merge.png
convert git-pull-request.svg -fuzz 50% -transparent white git-pull-request.png
convert github.svg -fuzz 50% -transparent white github.png
convert gitlab.svg -fuzz 50% -transparent white gitlab.png
convert globe.svg -fuzz 50% -transparent white globe.png
convert grid.svg -fuzz 50% -transparent white grid.png
convert hard-drive.svg -fuzz 50% -transparent white hard-drive.png
convert hash.svg -fuzz 50% -transparent white hash.png
convert headphones.svg -fuzz 50% -transparent white headphones.png
convert heart.svg -fuzz 50% -transparent white heart.png
convert help-circle.svg -fuzz 50% -transparent white help-circle.png
convert hexagon.svg -fuzz 50% -transparent white hexagon.png
convert home.svg -fuzz 50% -transparent white home.png
convert image.svg -fuzz 50% -transparent white image.png
convert inbox.svg -fuzz 50% -transparent white inbox.png
convert info.svg -fuzz 50% -transparent white info.png
convert instagram.svg -fuzz 50% -transparent white instagram.png
convert italic.svg -fuzz 50% -transparent white italic.png
convert key.svg -fuzz 50% -transparent white key.png
convert layers.svg -fuzz 50% -transparent white layers.png
convert layout.svg -fuzz 50% -transparent white layout.png
convert life-buoy.svg -fuzz 50% -transparent white life-buoy.png
convert link-2.svg -fuzz 50% -transparent white link-2.png
convert link.svg -fuzz 50% -transparent white link.png
convert linkedin.svg -fuzz 50% -transparent white linkedin.png
convert list.svg -fuzz 50% -transparent white list.png
convert loader.svg -fuzz 50% -transparent white loader.png
convert lock.svg -fuzz 50% -transparent white lock.png
convert log-in.svg -fuzz 50% -transparent white log-in.png
convert log-out.svg -fuzz 50% -transparent white log-out.png
convert mail.svg -fuzz 50% -transparent white mail.png
convert map-pin.svg -fuzz 50% -transparent white map-pin.png
convert map.svg -fuzz 50% -transparent white map.png
convert maximize-2.svg -fuzz 50% -transparent white maximize-2.png
convert maximize.svg -fuzz 50% -transparent white maximize.png
convert meh.svg -fuzz 50% -transparent white meh.png
convert menu.svg -fuzz 50% -transparent white menu.png
convert message-circle.svg -fuzz 50% -transparent white message-circle.png
convert message-square.svg -fuzz 50% -transparent white message-square.png
convert mic-off.svg -fuzz 50% -transparent white mic-off.png
convert mic.svg -fuzz 50% -transparent white mic.png
convert minimize-2.svg -fuzz 50% -transparent white minimize-2.png
convert minimize.svg -fuzz 50% -transparent white minimize.png
convert minus-circle.svg -fuzz 50% -transparent white minus-circle.png
convert minus-square.svg -fuzz 50% -transparent white minus-square.png
convert minus.svg -fuzz 50% -transparent white minus.png
convert monitor.svg -fuzz 50% -transparent white monitor.png
convert moon.svg -fuzz 50% -transparent white moon.png
convert more-horizontal.svg -fuzz 50% -transparent white more-horizontal.png
convert more-vertical.svg -fuzz 50% -transparent white more-vertical.png
convert mouse-pointer.svg -fuzz 50% -transparent white mouse-pointer.png
convert move.svg -fuzz 50% -transparent white move.png
convert music.svg -fuzz 50% -transparent white music.png
convert navigation-2.svg -fuzz 50% -transparent white navigation-2.png
convert navigation.svg -fuzz 50% -transparent white navigation.png
convert octagon.svg -fuzz 50% -transparent white octagon.png
convert package.svg -fuzz 50% -transparent white package.png
convert paperclip.svg -fuzz 50% -transparent white paperclip.png
convert pause-circle.svg -fuzz 50% -transparent white pause-circle.png
convert pause.svg -fuzz 50% -transparent white pause.png
convert pen-tool.svg -fuzz 50% -transparent white pen-tool.png
convert percent.svg -fuzz 50% -transparent white percent.png
convert phone-call.svg -fuzz 50% -transparent white phone-call.png
convert phone-forwarded.svg -fuzz 50% -transparent white phone-forwarded.png
convert phone-incoming.svg -fuzz 50% -transparent white phone-incoming.png
convert phone-missed.svg -fuzz 50% -transparent white phone-missed.png
convert phone-off.svg -fuzz 50% -transparent white phone-off.png
convert phone-outgoing.svg -fuzz 50% -transparent white phone-outgoing.png
convert phone.svg -fuzz 50% -transparent white phone.png
convert pie-chart.svg -fuzz 50% -transparent white pie-chart.png
convert play-circle.svg -fuzz 50% -transparent white play-circle.png
convert play.svg -fuzz 50% -transparent white play.png
convert plus-circle.svg -fuzz 50% -transparent white plus-circle.png
convert plus-square.svg -fuzz 50% -transparent white plus-square.png
convert plus.svg -fuzz 50% -transparent white plus.png
convert pocket.svg -fuzz 50% -transparent white pocket.png
convert power.svg -fuzz 50% -transparent white power.png
convert printer.svg -fuzz 50% -transparent white printer.png
convert radio.svg -fuzz 50% -transparent white radio.png
convert refresh-ccw.svg -fuzz 50% -transparent white refresh-ccw.png
convert refresh-cw.svg -fuzz 50% -transparent white refresh-cw.png
convert repeat.svg -fuzz 50% -transparent white repeat.png
convert rewind.svg -fuzz 50% -transparent white rewind.png
convert rotate-ccw.svg -fuzz 50% -transparent white rotate-ccw.png
convert rotate-cw.svg -fuzz 50% -transparent white rotate-cw.png
convert rss.svg -fuzz 50% -transparent white rss.png
convert save.svg -fuzz 50% -transparent white save.png
convert scissors.svg -fuzz 50% -transparent white scissors.png
convert search.svg -fuzz 50% -transparent white search.png
convert send.svg -fuzz 50% -transparent white send.png
convert server.svg -fuzz 50% -transparent white server.png
convert settings.svg -fuzz 50% -transparent white settings.png
convert share-2.svg -fuzz 50% -transparent white share-2.png
convert share.svg -fuzz 50% -transparent white share.png
convert shield-off.svg -fuzz 50% -transparent white shield-off.png
convert shield.svg -fuzz 50% -transparent white shield.png
convert shopping-bag.svg -fuzz 50% -transparent white shopping-bag.png
convert shopping-cart.svg -fuzz 50% -transparent white shopping-cart.png
convert shuffle.svg -fuzz 50% -transparent white shuffle.png
convert sidebar.svg -fuzz 50% -transparent white sidebar.png
convert skip-back.svg -fuzz 50% -transparent white skip-back.png
convert skip-forward.svg -fuzz 50% -transparent white skip-forward.png
convert slack.svg -fuzz 50% -transparent white slack.png
convert slash.svg -fuzz 50% -transparent white slash.png
convert sliders.svg -fuzz 50% -transparent white sliders.png
convert smartphone.svg -fuzz 50% -transparent white smartphone.png
convert smile.svg -fuzz 50% -transparent white smile.png
convert speaker.svg -fuzz 50% -transparent white speaker.png
convert square.svg -fuzz 50% -transparent white square.png
convert star.svg -fuzz 50% -transparent white star.png
convert stop-circle.svg -fuzz 50% -transparent white stop-circle.png
convert sun.svg -fuzz 50% -transparent white sun.png
convert sunrise.svg -fuzz 50% -transparent white sunrise.png
convert sunset.svg -fuzz 50% -transparent white sunset.png
convert table.svg -fuzz 50% -transparent white table.png
convert tablet.svg -fuzz 50% -transparent white tablet.png
convert tag.svg -fuzz 50% -transparent white tag.png
convert target.svg -fuzz 50% -transparent white target.png
convert terminal.svg -fuzz 50% -transparent white terminal.png
convert thermometer.svg -fuzz 50% -transparent white thermometer.png
convert thumbs-down.svg -fuzz 50% -transparent white thumbs-down.png
convert thumbs-up.svg -fuzz 50% -transparent white thumbs-up.png
convert toggle-left.svg -fuzz 50% -transparent white toggle-left.png
convert toggle-right.svg -fuzz 50% -transparent white toggle-right.png
convert tool.svg -fuzz 50% -transparent white tool.png
convert trash-2.svg -fuzz 50% -transparent white trash-2.png
convert trash.svg -fuzz 50% -transparent white trash.png
convert trello.svg -fuzz 50% -transparent white trello.png
convert trending-down.svg -fuzz 50% -transparent white trending-down.png
convert trending-up.svg -fuzz 50% -transparent white trending-up.png
convert triangle.svg -fuzz 50% -transparent white triangle.png
convert truck.svg -fuzz 50% -transparent white truck.png
convert tv.svg -fuzz 50% -transparent white tv.png
convert twitch.svg -fuzz 50% -transparent white twitch.png
convert twitter.svg -fuzz 50% -transparent white twitter.png
convert type.svg -fuzz 50% -transparent white type.png
convert umbrella.svg -fuzz 50% -transparent white umbrella.png
convert underline.svg -fuzz 50% -transparent white underline.png
convert unlock.svg -fuzz 50% -transparent white unlock.png
convert upload-cloud.svg -fuzz 50% -transparent white upload-cloud.png
convert upload.svg -fuzz 50% -transparent white upload.png
convert user-check.svg -fuzz 50% -transparent white user-check.png
convert user-minus.svg -fuzz 50% -transparent white user-minus.png
convert user-plus.svg -fuzz 50% -transparent white user-plus.png
convert user-x.svg -fuzz 50% -transparent white user-x.png
convert user.svg -fuzz 50% -transparent white user.png
convert users.svg -fuzz 50% -transparent white users.png
convert video-off.svg -fuzz 50% -transparent white video-off.png
convert video.svg -fuzz 50% -transparent white video.png
convert voicemail.svg -fuzz 50% -transparent white voicemail.png
convert volume-1.svg -fuzz 50% -transparent white volume-1.png
convert volume-2.svg -fuzz 50% -transparent white volume-2.png
convert volume-x.svg -fuzz 50% -transparent white volume-x.png
convert volume.svg -fuzz 50% -transparent white volume.png
convert watch.svg -fuzz 50% -transparent white watch.png
convert wifi-off.svg -fuzz 50% -transparent white wifi-off.png
convert wifi.svg -fuzz 50% -transparent white wifi.png
convert wind.svg -fuzz 50% -transparent white wind.png
convert x-circle.svg -fuzz 50% -transparent white x-circle.png
convert x-octagon.svg -fuzz 50% -transparent white x-octagon.png
convert x-square.svg -fuzz 50% -transparent white x-square.png
convert x.svg -fuzz 50% -transparent white x.png
convert youtube.svg -fuzz 50% -transparent white youtube.png
convert zap-off.svg -fuzz 50% -transparent white zap-off.png
convert zap.svg -fuzz 50% -transparent white zap.png
convert zoom-in.svg -fuzz 50% -transparent white zoom-in.png
convert zoom-out.svg -fuzz 50% -transparent white zoom-out.png
