/**
Copyright (c) 2008-2025 Geode Systems LLC
SPDX-License-Identifier: Apache-2.0
*/

package org.ramadda.geodata.gps;


import ucar.unidata.util.TwoFacedObject;

import java.util.ArrayList;


/**
 * Class description
 *
 *
 * @version        $version$, Sun, Mar 4, '12
 * @author         Enter your name here...
 */
public class Antenna {

    /** _more_ */
    public static final String NONE = "NONE                ";

    /** _more_ */
    private static ArrayList<TwoFacedObject> antennas;


    /** _more_ */
    private static final String[][] ANTENNAS = {
        { NONE,
          "NONE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;no&nbsp;antenna&nbsp;selected" },
        { "ACC2G1215A_XT_1 NONE",
          "ACC2G1215A_XT_1&nbsp;NONE&nbsp;ACTIVE&nbsp;L1/L2&nbsp;GPS,&nbsp;2.6,&nbsp;label&nbsp;top->N" },
        { "ACC3G1215A_XT_1 NONE",
          "ACC3G1215A_XT_1&nbsp;NONE&nbsp;ACTIVE&nbsp;L1/L2&nbsp;GPS,&nbsp;3.5,&nbsp;top&nbsp;of&nbsp;label->N" },
        { "ACC42G1215A_XT1 NONE",
          "ACC42G1215A_XT1&nbsp;NONE&nbsp;ACTIVE&nbsp;L1/L2&nbsp;GPS,&nbsp;743&nbsp;ARINC,&nbsp;ARROW->N" },
        { "ACC4G1215A_XT_1 NONE",
          "ACC4G1215A_XT_1&nbsp;NONE&nbsp;ACTIVE&nbsp;L1/L2&nbsp;GPS&nbsp;Mini&nbsp;ARINC,&nbsp;arrow->N" },
        { "ACC53G1215A_XT1 NONE",
          "ACC53G1215A_XT1&nbsp;NONE&nbsp;ACTIVE&nbsp;L1/L2&nbsp;GPS,&nbsp;5&nbsp;GP&nbsp;survey,&nbsp;RFC->N" },
        { "ACC53GO1215AXT1 NONE",
          "ACC53GO1215AXT1&nbsp;NONE&nbsp;L1/L2&nbsp;GPS/GLONASS,&nbsp;OMNISTAR,&nbsp;RFC->N" },
        { "ACC72GNSSA_XT_1 NONE",
          "ACC72GNSSA_XT_1&nbsp;NONE&nbsp;ACTIVE&nbsp;GNSS,&nbsp;7&nbsp;choke&nbsp;ring,&nbsp;RFC->N" },
        { "ACCG3ANT_3AT1   NONE",
          "ACCG3ANT_3AT1&nbsp;&nbsp;&nbsp;NONE&nbsp;ACTIVE&nbsp;L1&nbsp;GPS/GLON/OMNISTR,label&nbsp;top->N" },
        { "ACCG3ANT_42AT1  NONE",
          "ACCG3ANT_42AT1&nbsp;&nbsp;NONE&nbsp;ACTIVE&nbsp;L1&nbsp;GPS/GLONASS/OMNSTR,&nbsp;ARROW->N" },
        { "ACCG3ANT_52AT1  NONE",
          "ACCG3ANT_52AT1&nbsp;&nbsp;NONE&nbsp;ACTIVE&nbsp;L1&nbsp;GPS/GLONASS/OMNISTAR,&nbsp;RFC->N" },
        { "ACCG5ANT_2AT1   NONE",
          "ACCG5ANT_2AT1&nbsp;&nbsp;&nbsp;NONE&nbsp;ACTIVE&nbsp;L1/L2&nbsp;GPS/GLONASS,&nbsp;lable&nbsp;top->N" },
        { "ACCG5ANT_3AT1   NONE",
          "ACCG5ANT_3AT1&nbsp;&nbsp;&nbsp;NONE&nbsp;ACTIVE&nbsp;GPS/GLON./OMNISTAR,&nbsp;labeltop->N" },
        { "ACCG5ANT_42AT1  NONE",
          "ACCG5ANT_42AT1&nbsp;&nbsp;NONE&nbsp;ACTIVE&nbsp;GPS/GLONASS/OMNISTAR,&nbsp;arrow->N" },
        { "ACC_G5ANT_52AT1 NONE",
          "ACC_G5ANT_52AT1&nbsp;NONE&nbsp;ACTIVE&nbsp;GPS/GLON./OMNISTAR&nbsp;5&nbsp;GP,&nbsp;RFC->N" },
        { "ACC_G5ANT_72AT1 NONE",
          "ACC_G5ANT_72AT1&nbsp;NONE&nbsp;ACTIVE&nbsp;GPS/GLON./OMNISTAR&nbsp;7&nbsp;CR,&nbsp;RFC->N" },
        { "AERAT1675_120   NONE",
          "AERAT1675_120&nbsp;&nbsp;&nbsp;NONE&nbsp;AT1675-120W-NTPF-000-RG-39-NM-R&nbsp;arrow->N" },
        { "AERAT1675_120   SPKE",
          "AERAT1675_120&nbsp;&nbsp;&nbsp;SPKE&nbsp;AT1675-120W-NTPF-000-RG-39-NM-R&nbsp;arrow->N" },
        { "AERAT1675_182   NONE",
          "AERAT1675_182&nbsp;&nbsp;&nbsp;NONE&nbsp;GNSS&nbsp;Machine&nbsp;Control&nbsp;AT1675-182,&nbsp;RFC->N" },
        { "AERAT1675_200   NONE",
          "AERAT1675_200&nbsp;&nbsp;&nbsp;NONE&nbsp;AT1675-200W-TNCF-000-RG-39-NM-,&nbsp;arrow->N" },
        { "AERAT1675_200   SPKE",
          "AERAT1675_200&nbsp;&nbsp;&nbsp;SPKE&nbsp;AT1675-200W-TNCF-000-RG-39-NM-,&nbsp;arrow->N" },
        { "AERAT1675_29    NONE",
          "AERAT1675_29&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Aeroantenna&nbsp;L1/L2&nbsp;GPS&nbsp;+&nbsp;GLONASS&nbsp;Survey&nbsp;A" },
        { "AERAT1675_32    NONE",
          "AERAT1675_32&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS&nbsp;L1/L2,&nbsp;GLON&nbsp;G1/G2,&nbsp;L-BAND,&nbsp;RFC->N" },
        { "AERAT1675_382   NONE",
          "AERAT1675_382&nbsp;&nbsp;&nbsp;NONE&nbsp;TNCF-000-RG-39-NM,&nbsp;RF&nbsp;connector->North" },
        { "AERAT1675_39    NONE",
          "AERAT1675_39&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;MW-TNCFB-000-RG-26-,L1&nbsp;GPS/GLON,&nbsp;RFC->N" },
        { "AERAT1675_80    NONE",
          "AERAT1675_80&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;TNCF-000-RG-43-NM,&nbsp;top&nbsp;of&nbsp;label->North" },
        { "AERAT1675_81    NONE",
          "AERAT1675_81&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;AT1675-81W-TNCF-000-RG-39-NM,&nbsp;arrow->N" },
        { "AERAT2775_150   NONE",
          "AERAT2775_150&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2" },
        { "AERAT2775_159   NONE",
          "AERAT2775_159&nbsp;&nbsp;&nbsp;NONE&nbsp;AeroAnt&nbsp;AT2775-159W&nbsp;no&nbsp;radome" },
        { "AERAT2775_159   SPKE",
          "AERAT2775_159&nbsp;&nbsp;&nbsp;SPKE&nbsp;AeroAnt&nbsp;AT2775-159W&nbsp;+radome" },
        { "AERAT2775_160   NONE",
          "AERAT2775_160&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2" },
        { "AERAT2775_270   NONE",
          "AERAT2775_270&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2" },
        { "AERAT2775_382   NONE",
          "AERAT2775_382&nbsp;&nbsp;&nbsp;NONE&nbsp;TNCF-000-RG-39-NM,&nbsp;TNC&nbsp;RF&nbsp;connector->N" },
        { "AERAT2775_41    NONE",
          "AERAT2775_41&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Aviation&nbsp;L1/L2" },
        { "AERAT2775_42    NONE",
          "AERAT2775_42&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;L1/L2" },
        { "AERAT2775_42+CR NONE",
          "AERAT2775_42+CR&nbsp;NONE&nbsp;Marine&nbsp;III&nbsp;+CR&nbsp;adaptor" },
        { "AERAT2775_43    NONE",
          "AERAT2775_43&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Aeroantenna&nbsp;L1/L2&nbsp;GPS&nbsp;Survey&nbsp;AntennaCera" },
        { "AERAT2775_43    SPKE",
          "AERAT2775_43&nbsp;&nbsp;&nbsp;&nbsp;SPKE&nbsp;Aeroantenna&nbsp;L1/L2&nbsp;GPS&nbsp;Survey&nbsp;AntennaCera" },
        { "AERAT2775_443   NONE",
          "AERAT2775_443&nbsp;&nbsp;&nbsp;NONE&nbsp;AT2775-443W-NTPF-000-RG-39-NM&nbsp;&nbsp;&nbsp;Arrow->N" },
        { "AERAT2775_443   SPKE",
          "AERAT2775_443&nbsp;&nbsp;&nbsp;SPKE&nbsp;AT2775-443W-NTPF-000-RG-39-NM&nbsp;&nbsp;&nbsp;Arrow->N" },
        { "AERAT2775_62    NONE",
          "AERAT2775_62&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2" },
        { "AOA7490582.2    NONE",
          "AOA7490582.2&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:7490582-2,&nbsp;D/M&nbsp;chokering&nbsp;w/KWM&nbsp;LNA" },
        { "AOAD/M_B        NONE",
          "AOAD/M_B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings&nbsp;(Rogue,&nbsp;A" },
        { "AOAD/M_R        NONE",
          "AOAD/M_R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;R,&nbsp;chokerings&nbsp;(Rogue,JPL)" },
        { "AOAD/M_T        NONE",
          "AOAD/M_T&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings&nbsp;(TurboRog" },
        { "AOAD/M_TA_NGS   NONE",
          "AOAD/M_TA_NGS&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings&nbsp;(TurboRog" },
        { "AOARASCAL       NONE",
          "AOARASCAL&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Rascal&nbsp;RTK" },
        { "APSAPS-3        NONE",
          "APSAPS-3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;GPS&nbsp;L1/L2+L2C,&nbsp;GLO&nbsp;L1/L2&nbsp;ante" },
        { "APS_APS-3       NONE",
          "APS_APS-3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:10015,&nbsp;ALTUS&nbsp;GNSS&nbsp;RCVR/ANT,&nbsp;PNL&nbsp;TO&nbsp;N" },
        { "APS_APS-3       SCIT",
          "APS_APS-3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;P/N:10015,&nbsp;ALTUS&nbsp;GNSS&nbsp;RCVR/ANT,&nbsp;PNL&nbsp;TO&nbsp;N" },
        { "ASH110454       NONE",
          "ASH110454&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;ProMark2&nbsp;&nbsp;&nbsp;L1" },
        { "ASH111660       NONE",
          "ASH111660&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1&nbsp;GPS/GLONASS,&nbsp;base&nbsp;of&nbsp;RF&nbsp;connector->N" },
        { "ASH111661       NONE",
          "ASH111661&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GNSS&nbsp;Survey&nbsp;Antenna,&nbsp;base&nbsp;of&nbsp;RFC->N" },
        { "ASH700228A      NONE",
          "ASH700228A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;L1/L2&nbsp;Model&nbsp;700228A11.2&nbsp;inch&nbsp;gr" },
        { "ASH700228B      NONE",
          "ASH700228B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;L1/L2&nbsp;Model&nbsp;700228Bnew&nbsp;external" },
        { "ASH700228C      NONE",
          "ASH700228C&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;L1/L2&nbsp;Model&nbsp;700228Celiminated&nbsp;l" },
        { "ASH700228D      NONE",
          "ASH700228D&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;L1/L2&nbsp;REV.&nbsp;B&nbsp;700228D8&nbsp;L&nbsp;sha" },
        { "ASH700228E      NONE",
          "ASH700228E&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;L1/L2&nbsp;REV.&nbsp;B&nbsp;700228E&nbsp;(same&nbsp;as" },
        { "ASH700699.L1    NONE",
          "ASH700699.L1&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;700699B_Mar.III_L1" },
        { "ASH700700.A     NONE",
          "ASH700700.A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dual&nbsp;freq.&nbsp;marine&nbsp;antenna&nbsp;Model&nbsp;700700.A" },
        { "ASH700700.B     NONE",
          "ASH700700.B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dual&nbsp;freq.&nbsp;marine&nbsp;antenna&nbsp;Model&nbsp;700700.B" },
        { "ASH700700.C     NONE",
          "ASH700700.C&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dual&nbsp;freq.&nbsp;marine&nbsp;antenna&nbsp;Model&nbsp;700700.C" },
        { "ASH700718A      NONE",
          "ASH700718A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;III&nbsp;Whopper&nbsp;Model&nbsp;700718A14.5" },
        { "ASH700718B      NONE",
          "ASH700718B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;III&nbsp;Whopper&nbsp;Model&nbsp;700718B&nbsp;(sa" },
        { "ASH700829.2     SNOW",
          "ASH700829.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Geodetic&nbsp;III&nbsp;Whopper&nbsp;Model&nbsp;700829.2&nbsp;(U" },
        { "ASH700829.3     SNOW",
          "ASH700829.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Geodetic&nbsp;III&nbsp;Whopper&nbsp;Model&nbsp;700829.3&nbsp;(U" },
        { "ASH700829.A     SNOW",
          "ASH700829.A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Geodetic&nbsp;III&nbsp;Whopper&nbsp;Model&nbsp;700829.A&nbsp;(U" },
        { "ASH700829.A1    SNOW",
          "ASH700829.A1&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Geodetic&nbsp;III&nbsp;Whopper&nbsp;Model&nbsp;700829.A1&nbsp;(" },
        { "ASH700936A_M    NONE",
          "ASH700936A_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936A_M    SNOW",
          "ASH700936A_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936B_M    NONE",
          "ASH700936B_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936B_M    SNOW",
          "ASH700936B_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936C_M    NONE",
          "ASH700936C_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936C_M    SNOW",
          "ASH700936C_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936D_M    NONE",
          "ASH700936D_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936D_M    SCIS",
          "ASH700936D_M&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936D_M    SNOW",
          "ASH700936D_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936E      NONE",
          "ASH700936E&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936E      SNOW",
          "ASH700936E&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936E_C    NONE",
          "ASH700936E_C&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936E_C    SNOW",
          "ASH700936E_C&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH700936F_C    NONE",
          "ASH700936F_C&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701008.01B   NONE",
          "ASH701008.01B&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;IIIA,&nbsp;Model&nbsp;701008-01(B)" },
        { "ASH701073.1     NONE",
          "ASH701073.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS/GLONASS&nbsp;(GG)&nbsp;dual-frequency&nbsp;with&nbsp;cho" },
        { "ASH701073.3     NONE",
          "ASH701073.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Model&nbsp;701073&nbsp;REV&nbsp;3" },
        { "ASH701933A_M    NONE",
          "ASH701933A_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701933A_M    SNOW",
          "ASH701933A_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701933B_M    NONE",
          "ASH701933B_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701933B_M    SNOW",
          "ASH701933B_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701933C_M    NONE",
          "ASH701933C_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701933C_M    SCIS",
          "ASH701933C_M&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701933C_M    SCIT",
          "ASH701933C_M&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701933C_M    SNOW",
          "ASH701933C_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701941.1     NONE",
          "ASH701941.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dual&nbsp;Frequency&nbsp;GPS/GLONASS&nbsp;Model&nbsp;701941-" },
        { "ASH701941.2     NONE",
          "ASH701941.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dual&nbsp;Frequency&nbsp;GPS/GLONASS&nbsp;Model&nbsp;701941-" },
        { "ASH701941.A     NONE",
          "ASH701941.A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dual&nbsp;Frequency&nbsp;GPS/GLONASS&nbsp;Model&nbsp;701941-" },
        { "ASH701941.B     NONE",
          "ASH701941.B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dual&nbsp;Frequency&nbsp;GPS/GLONASS&nbsp;Model&nbsp;701941-" },
        { "ASH701941.B     SCIS",
          "ASH701941.B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dual&nbsp;Frequency&nbsp;GPS/GLONASS&nbsp;Model&nbsp;701941-" },
        { "ASH701945B_M    NONE",
          "ASH701945B_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945B_M    SCIS",
          "ASH701945B_M&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945B_M    SCIT",
          "ASH701945B_M&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945B_M    SNOW",
          "ASH701945B_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945C_M    NONE",
          "ASH701945C_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945C_M    OLGA",
          "ASH701945C_M&nbsp;&nbsp;&nbsp;&nbsp;OLGA&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945C_M    PFAN",
          "ASH701945C_M&nbsp;&nbsp;&nbsp;&nbsp;PFAN&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945C_M    SCIS",
          "ASH701945C_M&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945C_M    SCIT",
          "ASH701945C_M&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945C_M    SNOW",
          "ASH701945C_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945D_M    NONE",
          "ASH701945D_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945D_M    SCIS",
          "ASH701945D_M&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945D_M    SCIT",
          "ASH701945D_M&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945D_M    SNOW",
          "ASH701945D_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945E_M    NONE",
          "ASH701945E_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945E_M    SCIS",
          "ASH701945E_M&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945E_M    SCIT",
          "ASH701945E_M&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945E_M    SNOW",
          "ASH701945E_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945G_M    NONE",
          "ASH701945G_M&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945G_M    SCIS",
          "ASH701945G_M&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945G_M    SCIT",
          "ASH701945G_M&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701945G_M    SNOW",
          "ASH701945G_M&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;70" },
        { "ASH701946.2     NONE",
          "ASH701946.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,Model&nbsp;701" },
        { "ASH701946.2     SNOW",
          "ASH701946.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,Model&nbsp;701" },
        { "ASH701946.3     NONE",
          "ASH701946.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,Model&nbsp;701" },
        { "ASH701946.3     SNOW",
          "ASH701946.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,Model&nbsp;701" },
        { "ASH701975.01A   NONE",
          "ASH701975.01A&nbsp;&nbsp;&nbsp;NONE&nbsp;Geodetic&nbsp;IV,&nbsp;Rev&nbsp;A" },
        { "ASH701975.01AGP NONE",
          "ASH701975.01AGP&nbsp;NONE&nbsp;Geodetic&nbsp;IV,&nbsp;Rev&nbsp;A&nbsp;with&nbsp;groundplane" },
        { "ASH701975.01B   NONE",
          "ASH701975.01B&nbsp;&nbsp;&nbsp;NONE&nbsp;Rev:B,&nbsp;Geodetic&nbsp;IV" },
        { "ASH701975.01BGP NONE",
          "ASH701975.01BGP&nbsp;NONE&nbsp;Rev:B,&nbsp;Geodetic&nbsp;IV,&nbsp;w/Groundplane" },
        { "ASH802129       NONE",
          "ASH802129&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GNSS&nbsp;receiver,&nbsp;ProMark&nbsp;500,&nbsp;ctrl&nbsp;pnl->N" },
        { "ASH802147_A     NONE",
          "ASH802147_A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;ProMark&nbsp;800,&nbsp;PN&nbsp;802147&nbsp;A,&nbsp;LedDisplay->N" },
        { "ASH_LOCUS       NONE",
          "ASH_LOCUS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;L1&nbsp;only&nbsp;Display&nbsp;to&nbsp;South" },
        { "DGR_QEDGE       NONE",
          "DGR_QEDGE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;DataGrid&nbsp;QEDGE&nbsp;Active&nbsp;GPS&nbsp;L1L2&nbsp;by&nbsp;Gutec" },
        { "GUTGPSL1L2A     NONE",
          "GUTGPSL1L2A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2" },
        { "HARHX_GS488A    NONE",
          "HARHX_GS488A&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Model&nbsp;HX-GS488A&nbsp;GNSS&nbsp;RFC->South&nbsp;Arrow->N" },
        { "HEMA21          NONE",
          "HEMA21&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:804-3036-000#,&nbsp;L1&nbsp;GPS,&nbsp;RF&nbsp;conn->N" },
        { "HEMA52_WB       NONE",
          "HEMA52_WB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:804-3038-000#,&nbsp;Rev:X1,&nbsp;RF&nbsp;conn->N" },
        { "HEMS320         NONE",
          "HEMS320&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;GNSS&nbsp;ant/receiver&nbsp;display&nbsp;->N" },
        { "ITT3750323      NONE",
          "ITT3750323&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Chokering&nbsp;antenna&nbsp;with&nbsp;low&nbsp;noise&nbsp;amplifi" },
        { "ITT3750323      SCIS",
          "ITT3750323&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Chokering&nbsp;antenna&nbsp;with&nbsp;low&nbsp;noise&nbsp;amplifi" },
        { "JAVGRANT_G3     NONE",
          "JAVGRANT_G3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GrAnt-G3,&nbsp;01-574200-01,&nbsp;RF&nbsp;conn->N" },
        { "JAVGRANT_G3+GP  NONE",
          "JAVGRANT_G3+GP&nbsp;&nbsp;NONE&nbsp;01-574200-01,&nbsp;gnd&nbsp;plane&nbsp;+radome,&nbsp;RFC->N" },
        { "JAVGRANT_G3+GP  JVGR",
          "JAVGRANT_G3+GP&nbsp;&nbsp;JVGR&nbsp;01-574200-01,&nbsp;gnd&nbsp;plane&nbsp;+radome,&nbsp;RFC->N" },
        { "JAVRINGANT_DM   NONE",
          "JAVRINGANT_DM&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAVRINGANT_DM   JVDM",
          "JAVRINGANT_DM&nbsp;&nbsp;&nbsp;JVDM&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAVRINGANT_DM   SCIS",
          "JAVRINGANT_DM&nbsp;&nbsp;&nbsp;SCIS&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAVRINGANT_DM   SCIT",
          "JAVRINGANT_DM&nbsp;&nbsp;&nbsp;SCIT&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAVTRIANT       NONE",
          "JAVTRIANT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAVTRIUMPH_VS   NONE",
          "JAVTRIUMPH_VS&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLONASS&nbsp;L1/L2," },
        { "JAV_GRANT-G3T   NONE",
          "JAV_GRANT-G3T&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAV_RINGANT_G3T NONE",
          "JAV_RINGANT_G3T&nbsp;NONE&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAV_RINGANT_G3T JAVC",
          "JAV_RINGANT_G3T&nbsp;JAVC&nbsp;External&nbsp;GPS&nbsp;L1/L2/L5,&nbsp;GLO&nbsp;L1/L2,&nbsp;GAL&nbsp;E1" },
        { "JAV_TRIUMPH-1   NONE",
          "JAV_TRIUMPH-1&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;GPS&nbsp;L1/L2/L2C/L5,&nbsp;GLONASS&nbsp;L1/" },
        { "JNSCHOKERING_DM NONE",
          "JNSCHOKERING_DM&nbsp;NONE&nbsp;Choke&nbsp;Ring&nbsp;-Radome" },
        { "JNSCR_C146-22-1 NONE",
          "JNSCR_C146-22-1&nbsp;NONE&nbsp;L1/L2&nbsp;CR&nbsp;DM-T&nbsp;case&nbsp;w/C146-22-1&nbsp;element" },
        { "JNSCR_C146-22-1 SCIS",
          "JNSCR_C146-22-1&nbsp;SCIS&nbsp;L1/L2&nbsp;CR&nbsp;DM-T&nbsp;case&nbsp;w/radome" },
        { "JNSMARANT_GGD   NONE",
          "JNSMARANT_GGD&nbsp;&nbsp;&nbsp;NONE&nbsp;low-profile,&nbsp;waterproof&nbsp;GPS/GLONASS&nbsp;exte" },
        { "JPLD/M_R        NONE",
          "JPLD/M_R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;with&nbsp;chokerings(R" },
        { "JPLD/M_RA_SOP   NONE",
          "JPLD/M_RA_SOP&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings&nbsp;(Rogue,&nbsp;J" },
        { "JPSLEGANT_E     NONE",
          "JPSLEGANT_E&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Antenna&nbsp;on&nbsp;flat&nbsp;groundplane" },
        { "JPSMARANT_GGD   NONE",
          "JPSMARANT_GGD&nbsp;&nbsp;&nbsp;NONE&nbsp;JNSMARANT_GGD" },
        { "JPSODYSSEY_I    NONE",
          "JPSODYSSEY_I&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Antenna&nbsp;on&nbsp;flat&nbsp;groundplane,integrated&nbsp;w" },
        { "JPSREGANT_DD_E  NONE",
          "JPSREGANT_DD_E&nbsp;&nbsp;NONE&nbsp;Dual-depth&nbsp;chokering&nbsp;antenna,&nbsp;external" },
        { "JPSREGANT_SD_E  NONE",
          "JPSREGANT_SD_E&nbsp;&nbsp;NONE&nbsp;Single-depth&nbsp;chokering&nbsp;antenna,&nbsp;external" },
        { "LEIAR10         NONE",
          "LEIAR10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Multi-purpose&nbsp;geodetic&nbsp;reference&nbsp;station" },
        { "LEIAR25         NONE",
          "LEIAR25&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25         LEIT",
          "LEIAR25&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LEIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25         SCIS",
          "LEIAR25&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25         SCIT",
          "LEIAR25&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R3      NONE",
          "LEIAR25.R3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R3      LEIT",
          "LEIAR25.R3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LEIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R3      SCIS",
          "LEIAR25.R3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R3      SCIT",
          "LEIAR25.R3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R4      NONE",
          "LEIAR25.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R4      LEIT",
          "LEIAR25.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LEIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R4      SCIS",
          "LEIAR25.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAR25.R4      SCIT",
          "LEIAR25.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;(Revis" },
        { "LEIAS05         NONE",
          "LEIAS05&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;geodetic&nbsp;antenna&nbsp;L1,&nbsp;SmartTrack" },
        { "LEIAS10         NONE",
          "LEIAS10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;geodetic&nbsp;antenna,&nbsp;SmartTrack+&nbsp;w" },
        { "LEIAT202+GP     NONE",
          "LEIAT202+GP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;micropulse&nbsp;antenna&nbsp;L1/L2,&nbsp;with" },
        { "LEIAT202-GP     NONE",
          "LEIAT202-GP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;micropulse&nbsp;antenna&nbsp;L1/L2,&nbsp;no&nbsp;gr" },
        { "LEIAT302+GP     NONE",
          "LEIAT302+GP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;micropulse&nbsp;antenna&nbsp;L1/L2,&nbsp;with" },
        { "LEIAT302-GP     NONE",
          "LEIAT302-GP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;micropulse&nbsp;antenna&nbsp;L1/L2,&nbsp;no&nbsp;gr" },
        { "LEIAT303        NONE",
          "LEIAT303&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Micropulse&nbsp;antenna&nbsp;L1/L2,&nbsp;with&nbsp;chokering" },
        { "LEIAT303        LEIC",
          "LEIAT303&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LEIC&nbsp;Micropulse&nbsp;antenna&nbsp;L1/L2,&nbsp;with&nbsp;chokering" },
        { "LEIAT502        NONE",
          "LEIAT502&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;antenna&nbsp;with&nbsp;Aero&nbsp;element&nbsp;L1/L2" },
        { "LEIAT503        NONE",
          "LEIAT503&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Micropulse&nbsp;antenna&nbsp;with&nbsp;chokerings,&nbsp;L1/L" },
        { "LEIAT503        LEIC",
          "LEIAT503&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LEIC&nbsp;Micropulse&nbsp;antenna&nbsp;with&nbsp;chokerings,&nbsp;L1/L" },
        { "LEIAT504        NONE",
          "LEIAT504&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIAT504        LEIS",
          "LEIAT504&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LEIS&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIAT504        OLGA",
          "LEIAT504&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OLGA&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIAT504        SCIS",
          "LEIAT504&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIAT504GG      NONE",
          "LEIAT504GG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIAT504GG      LEIS",
          "LEIAT504GG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LEIS&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIAT504GG      SCIS",
          "LEIAT504GG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIAT504GG      SCIT",
          "LEIAT504GG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;antenna&nbsp;with&nbsp;choker" },
        { "LEIATX1230      NONE",
          "LEIATX1230&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIATX1230+GNSS NONE",
          "LEIATX1230+GNSS&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna,&nbsp;SmartTrack+,G" },
        { "LEIATX1230GG    NONE",
          "LEIATX1230GG&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIAX1202       NONE",
          "LEIAX1202&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIAX1202A      NONE",
          "LEIAX1202A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Rev:1.01,&nbsp;L1/L2" },
        { "LEIAX1202GG     NONE",
          "LEIAX1202GG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;External&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIAX1203+GNSS  NONE",
          "LEIAX1203+GNSS&nbsp;&nbsp;NONE&nbsp;External&nbsp;geodetic&nbsp;antenna,&nbsp;SmartTrack+&nbsp;w" },
        { "LEIGG02PLUS     NONE",
          "LEIGG02PLUS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIGS08         NONE",
          "LEIGS08&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIGS09         NONE",
          "LEIGS09&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIGS12         NONE",
          "LEIGS12&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEIGS15         NONE",
          "LEIGS15&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna,&nbsp;SmartTrack+,G" },
        { "LEIMNA950GG     NONE",
          "LEIMNA950GG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;geodetic&nbsp;antenna&nbsp;L1/L2,&nbsp;SmartTr" },
        { "LEISR299_INT    NONE",
          "LEISR299_INT&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Internal&nbsp;antenna&nbsp;with&nbsp;Ball&nbsp;element&nbsp;L1/L2" },
        { "LEISR399_INT    NONE",
          "LEISR399_INT&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Revised&nbsp;antenna&nbsp;with&nbsp;modified&nbsp;mount&nbsp;desi" },
        { "LEISR399_INTA   NONE",
          "LEISR399_INTA&nbsp;&nbsp;&nbsp;NONE&nbsp;Original&nbsp;internal&nbsp;antenna&nbsp;with&nbsp;Ball&nbsp;elem" },
        { "MAC4647942      NONE",
          "MAC4647942&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Crossed-dipole&nbsp;antenna&nbsp;with&nbsp;large&nbsp;ground" },
        { "MAC4647942      MMAC",
          "MAC4647942&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MMAC&nbsp;Crossed-dipole&nbsp;antenna&nbsp;with&nbsp;large&nbsp;ground" },
        { "MAG105645       NONE",
          "MAG105645&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;GPS" },
        { "MAG111406       NONE",
          "MAG111406&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:111406,&nbsp;(AT1675-7MW),North:&nbsp;RF&nbsp;CONN" },
        { "MAG990596       NONE",
          "MAG990596&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;PROMARK500,&nbsp;TNC&nbsp;CONNECTOR&nbsp;TO&nbsp;NORTH" },
        { "MPL1230         NONE",
          "MPL1230&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;Surveying,&nbsp;Choke&nbsp;Ring" },
        { "MPL1370W        NONE",
          "MPL1370W&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1" },
        { "MPLL1/L2_SURV   NONE",
          "MPLL1/L2_SURV&nbsp;&nbsp;&nbsp;NONE&nbsp;MicroPulse&nbsp;L1/L2&nbsp;GPS&nbsp;Surveying&nbsp;Antenna&nbsp;9" },
        { "MPL_WAAS_2224NW NONE",
          "MPL_WAAS_2224NW&nbsp;NONE&nbsp;MicroPulse&nbsp;WAAS&nbsp;Unit&nbsp;2224NW" },
        { "MPL_WAAS_2225NW NONE",
          "MPL_WAAS_2225NW&nbsp;NONE&nbsp;MicroPulse&nbsp;WAAS&nbsp;L1/L2/L5&nbsp;2225NW" },
        { "NAVAN2004T      NONE",
          "NAVAN2004T&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS&nbsp;L1/L2/L-Band&nbsp;Antenna,&nbsp;Survey&nbsp;Mount" },
        { "NAVAN2008T      NONE",
          "NAVAN2008T&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS&nbsp;L1/L2/L-Band&nbsp;Antenna,&nbsp;Aircraft&nbsp;Mount" },
        { "NAVANT3001A     NONE",
          "NAVANT3001A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Quasar,&nbsp;see&nbsp;also&nbsp;AERAT1675_81,&nbsp;arrow->N" },
        { "NAVANT3001B     NONE",
          "NAVANT3001B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GNSS&nbsp;BASE&nbsp;Choke&nbsp;Ring&nbsp;Antenna,&nbsp;arrow->N" },
        { "NAVRT3010S      NONE",
          "NAVRT3010S&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;RTK&nbsp;GPS&nbsp;Antenna+Receiver" },
        { "NAVSF2040G      NONE",
          "NAVSF2040G&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS&nbsp;L1/L2/SBAS/StarFire&nbsp;Antenna" },
        { "NAVSF3040       NONE",
          "NAVSF3040&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;NavCom&nbsp;RTK/StarFire&nbsp;GNSS&nbsp;Antenna+Receive" },
        { "NAV_ANT3001BR   SPKE",
          "NAV_ANT3001BR&nbsp;&nbsp;&nbsp;SPKE&nbsp;GNSS&nbsp;BASE&nbsp;CR,&nbsp;aka:&nbsp;AT1675-20W,&nbsp;arrow->N" },
        { "NAV_ANT3001R    NONE",
          "NAV_ANT3001R&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GNSS&nbsp;ROVER,&nbsp;aka:&nbsp;AT1675-82W,&nbsp;RFconn->N" },
        { "NAX3G+C         NONE",
          "NAX3G+C&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;3G+C&nbsp;one-layer&nbsp;GNSS&nbsp;antenna&nbsp;for&nbsp;all&nbsp;sign" },
        { "NGSD/M+GP60     NONE",
          "NGSD/M+GP60&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;D/M&nbsp;antenna&nbsp;with&nbsp;extended&nbsp;groundplane" },
        { "NOV501          NONE",
          "NOV501&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-501&nbsp;L1" },
        { "NOV501+CR       NONE",
          "NOV501+CR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-501&nbsp;L1&nbsp;with&nbsp;chokerings" },
        { "NOV502          NONE",
          "NOV502&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-502&nbsp;L1/L2" },
        { "NOV502+CR       NONE",
          "NOV502+CR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-502&nbsp;L1/L2&nbsp;with&nbsp;chokerings" },
        { "NOV503+CR       NONE",
          "NOV503+CR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-503&nbsp;L1/L2&nbsp;with&nbsp;chokerings" },
        { "NOV503+CR       SPKE",
          "NOV503+CR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SPKE&nbsp;GPS-503&nbsp;L1/L2&nbsp;with&nbsp;chokerings" },
        { "NOV512          NONE",
          "NOV512&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Aviation&nbsp;L1/L2" },
        { "NOV531          NONE",
          "NOV531&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-531&nbsp;L1" },
        { "NOV531+CR       NONE",
          "NOV531+CR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-531&nbsp;L1&nbsp;with&nbsp;chokerings" },
        { "NOV533          RADM",
          "NOV533&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RADM&nbsp;L1/L2&nbsp;compact&nbsp;CR,&nbsp;ANT-533&nbsp;w/radome" },
        { "NOV600          NONE",
          "NOV600&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;GPS&nbsp;Antenna&nbsp;(Pinwheel&nbsp;Technology)" },
        { "NOV701GGL       NONE",
          "NOV701GGL&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-701GG&nbsp;GPS&nbsp;L1,&nbsp;GLONASS&nbsp;L1,&nbsp;L-Band&nbsp;(Pi" },
        { "NOV701GG_1.03   NONE",
          "NOV701GG_1.03&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01017576,&nbsp;Rev:1.03,&nbsp;GPS-701-GG" },
        { "NOV702          NONE",
          "NOV702&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-702&nbsp;RoHS-compliant&nbsp;GPS&nbsp;L1/L2&nbsp;&nbsp;(Pinwh" },
        { "NOV702GG        NONE",
          "NOV702GG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS-702GG&nbsp;GPS&nbsp;L1/L2,&nbsp;GLONASS&nbsp;L1/L2&nbsp;(Pinw" },
        { "NOV702GGL_1.01  NONE",
          "NOV702GGL_1.01&nbsp;&nbsp;NONE&nbsp;P/N:01017939,&nbsp;Rev:1.01,&nbsp;GPS-702-GGL" },
        { "NOV702GG_1.02   NONE",
          "NOV702GG_1.02&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01017577,&nbsp;Rev:1.02,&nbsp;GPS-702-GG" },
        { "NOV702GG_1.03   NONE",
          "NOV702GG_1.03&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01017577,&nbsp;Rev:1.03,&nbsp;GPS-702-GG" },
        { "NOV702L_1.01    NONE",
          "NOV702L_1.01&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01017509,&nbsp;Rev:1.01,&nbsp;GPS-702L" },
        { "NOV702L_1.03    NONE",
          "NOV702L_1.03&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01017509,&nbsp;Rev:1.03,&nbsp;GPS-702L" },
        { "NOV702_2.02     NONE",
          "NOV702_2.02&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Rev:2.02,&nbsp;GPS-702&nbsp;L1/L2" },
        { "NOV702_3.00     NONE",
          "NOV702_3.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Rev:3.00,&nbsp;GPS-702&nbsp;L1/L2" },
        { "NOV750.R4       NONE",
          "NOV750.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;ground" },
        { "NOV750.R4       NOVS",
          "NOV750.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NOVS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;ground" },
        { "NOV750.R4       SCIS",
          "NOV750.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;ground" },
        { "NOV750.R4       SCIT",
          "NOV750.R4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;3D&nbsp;choke&nbsp;ring&nbsp;ground" },
        { "NOV_WAAS_600    NONE",
          "NOV_WAAS_600&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;NOV600&nbsp;element&nbsp;in&nbsp;MPL&nbsp;assembly&nbsp;(used&nbsp;by" },
        { "SEN67157514     NONE",
          "SEN67157514&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:S67-1575-14,&nbsp;L1/L2,&nbsp;(+26dB&nbsp;amp)" },
        { "SEN67157514+CR  NONE",
          "SEN67157514+CR&nbsp;&nbsp;NONE&nbsp;P/N:S67-1575-14,&nbsp;L1/L2,&nbsp;(+26dB&nbsp;amp),&nbsp;+cr" },
        { "SEN67157549     NONE",
          "SEN67157549&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:S67-1575-49,&nbsp;L1" },
        { "SEN67157549+CR  NONE",
          "SEN67157549+CR&nbsp;&nbsp;NONE&nbsp;P/N:S67-1575-49,&nbsp;L1,&nbsp;+chokerings" },
        { "SEN67157596     NONE",
          "SEN67157596&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:S67-1575-96,&nbsp;L1/L2" },
        { "SEN67157596+CR  NONE",
          "SEN67157596+CR&nbsp;&nbsp;NONE&nbsp;Sensor&nbsp;Systems&nbsp;L1/L2,&nbsp;PN:S67-1575-96&nbsp;+&nbsp;c" },
        { "SEPCHOKE_MC     NONE",
          "SEPCHOKE_MC&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;multi-constellation&nbsp;choke&nbsp;ringGPS/GAL/CO" },
        { "SEPCHOKE_MC     SPKE",
          "SEPCHOKE_MC&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SPKE&nbsp;multi-constellation&nbsp;choke&nbsp;ringGPS/GAL/CO" },
        { "SEP_POLANT+     NONE",
          "SEP_POLANT+&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GPS&nbsp;L1/L2,&nbsp;AT2775-229S,&nbsp;N&nbsp;arrow&nbsp;on&nbsp;top" },
        { "SEP_POLANT+_GG  NONE",
          "SEP_POLANT+_GG&nbsp;&nbsp;NONE&nbsp;GNSS&nbsp;L1/L2,&nbsp;AT1675-29S,&nbsp;N&nbsp;arrow&nbsp;on&nbsp;top" },
        { "SMICR3B         NONE",
          "SMICR3B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;AeroAnt&nbsp;AT2775-159W&nbsp;no&nbsp;radome" },
        { "SMICR3B         SPKE",
          "SMICR3B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SPKE&nbsp;AeroAnt&nbsp;AT2775-159W&nbsp;+radome" },
        { "SOK502          NONE",
          "SOK502&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;SK520&nbsp;L1/L2&nbsp;GPS&nbsp;antenna" },
        { "SOK600          NONE",
          "SOK600&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;SK600&nbsp;L1/L2&nbsp;GPS&nbsp;antenna" },
        { "SOK702          NONE",
          "SOK702&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;SK702&nbsp;L1/L2&nbsp;GPS&nbsp;antenna" },
        { "SOKA110         NONE",
          "SOKA110&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;A110&nbsp;(L1)" },
        { "SOKA120         NONE",
          "SOKA120&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;A120&nbsp;(L1/L2)" },
        { "SOKGRX1         NONE",
          "SOKGRX1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01-090101-08,&nbsp;L1L2,&nbsp;TPS&nbsp;ctrl&nbsp;pnl->N" },
        { "SOKGRX1+10      NONE",
          "SOKGRX1+10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01-090101-08,&nbsp;10-cm&nbsp;standoff#808100" },
        { "SOKSTRATUS      NONE",
          "SOKSTRATUS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;Stratus&nbsp;(L1)" },
        { "SOK_GSR2700IS   NONE",
          "SOK_GSR2700IS&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;GSR2700&nbsp;IS&nbsp;(L1/L2)&nbsp;Pinwheel&nbsp;Tech" },
        { "SOK_GSR2700ISX  NONE",
          "SOK_GSR2700ISX&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;GSR2700&nbsp;ISX,&nbsp;14&nbsp;GPS&nbsp;L1,&nbsp;14&nbsp;GPS&nbsp;L2" },
        { "SOK_LOCUS       NONE",
          "SOK_LOCUS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Sokkia&nbsp;Locus&nbsp;(L1,&nbsp;display&nbsp;to&nbsp;South&nbsp;)" },
        { "SOK_RADIAN_IS   NONE",
          "SOK_RADIAN_IS&nbsp;&nbsp;&nbsp;NONE&nbsp;Radian&nbsp;IS&nbsp;L1/L2&nbsp;RTK&nbsp;GPS&nbsp;integrated&nbsp;recei" },
        { "SPP39105.90     NONE",
          "SPP39105.90&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Epoch&nbsp;L1/L2&nbsp;w/o&nbsp;GP" },
        { "SPP571212238+GP NONE",
          "SPP571212238+GP&nbsp;NONE&nbsp;Spectra&nbsp;Precision&nbsp;groundplane" },
        { "SPP571908273+CR NONE",
          "SPP571908273+CR&nbsp;NONE&nbsp;chokerings,&nbsp;oblong&nbsp;antenna&nbsp;element" },
        { "SPP571908273+CR SPKE",
          "SPP571908273+CR&nbsp;SPKE&nbsp;CR,&nbsp;oblong&nbsp;antenna&nbsp;element,&nbsp;+rd" },
        { "SPP67410_42     NONE",
          "SPP67410_42&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;EPOCH&nbsp;35&nbsp;Rover&nbsp;GPS/GLONASS,&nbsp;LED&nbsp;disp.->N" },
        { "SPP67410_44     NONE",
          "SPP67410_44&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;EPOCH&nbsp;35&nbsp;Rover&nbsp;GPS/GLONASS,&nbsp;LED&nbsp;disp.->N" },
        { "SPP67410_46     NONE",
          "SPP67410_46&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;EPOCH&nbsp;35&nbsp;Rover&nbsp;GPS/GLONASS,&nbsp;LED&nbsp;disp.->N" },
        { "SPP68410_10     NONE",
          "SPP68410_10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;EPOCH&nbsp;50&nbsp;GNSS&nbsp;Receiver&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LED&nbsp;disp.->N" },
        { "STXS9SA7224V3.0 NONE",
          "STXS9SA7224V3.0&nbsp;NONE&nbsp;Integrated&nbsp;GPS&nbsp;L1/L2+L2C/L5,&nbsp;GLONASS,&nbsp;Ga" },
        { "THA800961+REC   NONE",
          "THA800961+REC&nbsp;&nbsp;&nbsp;NONE&nbsp;Z-Max&nbsp;receiver&nbsp;+&nbsp;ant" },
        { "THA800961+RTK   NONE",
          "THA800961+RTK&nbsp;&nbsp;&nbsp;NONE&nbsp;Z-Max&nbsp;w/RTK&nbsp;adaptor" },
        { "THA800961RECUHF NONE",
          "THA800961RECUHF&nbsp;NONE&nbsp;Z-Max&nbsp;receiver&nbsp;+UHF&nbsp;Vortex&nbsp;adaptor" },
        { "THA800961RTKUHF NONE",
          "THA800961RTKUHF&nbsp;NONE&nbsp;Z-Max&nbsp;Receiver+RTK+UHF&nbsp;Vortex&nbsp;adaptors" },
        { "THANAP002       NONE",
          "THANAP002&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;microstrip,&nbsp;Geodetic" },
        { "TOP700779A      NONE",
          "TOP700779A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Model&nbsp;700779.A&nbsp;(same&nbsp;as&nbsp;ASH700718A)" },
        { "TOP72110        NONE",
          "TOP72110&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Model&nbsp;72110,&nbsp;used&nbsp;with&nbsp;the&nbsp;TURBO-SII&nbsp;rec" },
        { "TPSCR.G3        NONE",
          "TPSCR.G3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Topcon&nbsp;GPS/GLONASS/Galileo&nbsp;choke&nbsp;ring&nbsp;an" },
        { "TPSCR.G3        SCIS",
          "TPSCR.G3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Topcon&nbsp;GPS/GLONASS/Galileo&nbsp;choke&nbsp;ring&nbsp;an" },
        { "TPSCR.G3        SCIT",
          "TPSCR.G3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Topcon&nbsp;GPS/GLONASS/Galileo&nbsp;choke&nbsp;ring&nbsp;an" },
        { "TPSCR.G3        TPSH",
          "TPSCR.G3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TPSH&nbsp;Topcon&nbsp;GPS/GLONASS/Galileo&nbsp;choke&nbsp;ring&nbsp;an" },
        { "TPSCR.G5        NONE",
          "TPSCR.G5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;CR-G5&nbsp;Full&nbsp;Wave&nbsp;Geodetic,&nbsp;arrow/RFC->N" },
        { "TPSCR.G5        SCIS",
          "TPSCR.G5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;CR-G5&nbsp;Full&nbsp;Wave&nbsp;Geodetic,&nbsp;arrow/RFC->N" },
        { "TPSCR.G5        SCIT",
          "TPSCR.G5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;CR-G5&nbsp;Full&nbsp;Wave&nbsp;Geodetic,&nbsp;arrow/RFC->N" },
        { "TPSCR.G5        TPSH",
          "TPSCR.G5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TPSH&nbsp;CR-G5&nbsp;Full&nbsp;Wave&nbsp;Geodetic,&nbsp;arrow/RFC->N" },
        { "TPSCR3_GGD      NONE",
          "TPSCR3_GGD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Part&nbsp;No.&nbsp;01-031401-01" },
        { "TPSCR3_GGD      CONE",
          "TPSCR3_GGD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CONE&nbsp;Part&nbsp;No.&nbsp;01-031401-01" },
        { "TPSCR3_GGD      OLGA",
          "TPSCR3_GGD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OLGA&nbsp;Part&nbsp;No.&nbsp;01-031401-01" },
        { "TPSCR3_GGD      PFAN",
          "TPSCR3_GGD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PFAN&nbsp;Part&nbsp;No.&nbsp;01-031401-01" },
        { "TPSCR4          NONE",
          "TPSCR4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-840002-01&nbsp;Choke&nbsp;ring&nbsp;L1/L2" },
        { "TPSCR4          CONE",
          "TPSCR4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CONE&nbsp;P/N&nbsp;01-840002-01&nbsp;Choke&nbsp;ring&nbsp;L1/L2" },
        { "TPSG3_A1        NONE",
          "TPSG3_A1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Topcon&nbsp;GPS/GLONASS/Galileo&nbsp;antenna&nbsp;with" },
        { "TPSG3_A1        TPSD",
          "TPSG3_A1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TPSD&nbsp;Topcon&nbsp;GPS/GLONASS/Galileo&nbsp;antenna&nbsp;with" },
        { "TPSGR3          NONE",
          "TPSGR3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;antenna/receiver/modem&nbsp;GNSS&nbsp;L" },
        { "TPSGR5          NONE",
          "TPSGR5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01-090101-23,&nbsp;Integrated,&nbsp;model&nbsp;GR-5" },
        { "TPSHIPER_GD     NONE",
          "TPSHIPER_GD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-830401-01&nbsp;Integrated&nbsp;antenna+rece" },
        { "TPSHIPER_GGD    NONE",
          "TPSHIPER_GGD&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-840401-01&nbsp;Antenna+receiver&nbsp;GPS/GL" },
        { "TPSHIPER_II     NONE",
          "TPSHIPER_II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01-861901-05,&nbsp;HiPerII,&nbsp;ctrl&nbsp;pnl->N" },
        { "TPSHIPER_II+10  NONE",
          "TPSHIPER_II+10&nbsp;&nbsp;NONE&nbsp;P/N:01-861901-05,&nbsp;10-cm&nbsp;standoff&nbsp;#51949" },
        { "TPSHIPER_LITE   NONE",
          "TPSHIPER_LITE&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-840802-03&nbsp;Antenna+receiver+wirele" },
        { "TPSHIPER_PLUS   NONE",
          "TPSHIPER_PLUS&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-840801-01&nbsp;Antenna+receiver+wirele" },
        { "TPSHIPER_XT     NONE",
          "TPSHIPER_XT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Model&nbsp;TPSHIPER_LITE&nbsp;with&nbsp;SIMM&nbsp;card" },
        { "TPSLEGANT       NONE",
          "TPSLEGANT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;LegAnt,&nbsp;P/N&nbsp;:&nbsp;01-830004-01,Arrow->N" },
        { "TPSLEGANT2      NONE",
          "TPSLEGANT2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-830004-02&nbsp;L1/L2" },
        { "TPSLEGANT3_UHF  NONE",
          "TPSLEGANT3_UHF&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-830004-03&nbsp;L1/L2" },
        { "TPSLEGANT_G     NONE",
          "TPSLEGANT_G&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-830005-01&nbsp;L1" },
        { "TPSMAPANT_B     NONE",
          "TPSMAPANT_B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1" },
        { "TPSMG_A2        NONE",
          "TPSMG_A2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2" },
        { "TPSODYSSEY_I    NONE",
          "TPSODYSSEY_I&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;antenna/receiver&nbsp;L1/L2" },
        { "TPSPG_A1        NONE",
          "TPSPG_A1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-840201-04&nbsp;L1/L2&nbsp;without&nbsp;groundpla" },
        { "TPSPG_A1        TPSD",
          "TPSPG_A1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TPSD&nbsp;P/N&nbsp;01-840201-04&nbsp;L1/L2&nbsp;without&nbsp;groundpla" },
        { "TPSPG_A1+GP     NONE",
          "TPSPG_A1+GP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-840201-04&nbsp;L1/L2&nbsp;with&nbsp;groundplane" },
        { "TPSPG_A1_6+GP   NONE",
          "TPSPG_A1_6+GP&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01-840201-06,&nbsp;PG-A1&nbsp;w/GP,&nbsp;arrow->N" },
        { "TPSPG_A2        NONE",
          "TPSPG_A2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;microstrip" },
        { "TPSPG_A5        NONE",
          "TPSPG_A5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1" },
        { "TPSPG_S1        NONE",
          "TPSPG_S1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-100301-01&nbsp;&nbsp;&nbsp;&nbsp;without&nbsp;groundplane" },
        { "TPSPG_S1+GP     NONE",
          "TPSPG_S1+GP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N&nbsp;01-100301-01&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with&nbsp;groundplane" },
        { "TPSPN.A5        NONE",
          "TPSPN.A5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;PN-A5&nbsp;Full&nbsp;Wave&nbsp;semi-hemispher'l,&nbsp;RFC>N" },
        { "TPSPN.A5        SCIS",
          "TPSPN.A5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;PN-A5&nbsp;Full&nbsp;Wave&nbsp;semi-hemispher'l,&nbsp;RFC>N" },
        { "TPSPN.A5        SCIT",
          "TPSPN.A5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;PN-A5&nbsp;Full&nbsp;Wave&nbsp;semi-heispherical&nbsp;RFC=N" },
        { "TPSPN.A5        TPSH",
          "TPSPN.A5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TPSH&nbsp;PN-A5&nbsp;Full&nbsp;Wave&nbsp;semi-hemispher'l,&nbsp;RFC>N" },
        { "TPS_CR.3        SCIS",
          "TPS_CR.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;P/N:01-031401-01,&nbsp;radome&nbsp;#0010" },
        { "TPS_CR4+RD      SCIS",
          "TPS_CR4+RD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Choke&nbsp;Ring+rd" },
        { "TPS_MC.A5       NONE",
          "TPS_MC.A5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:01-841001-01,&nbsp;Topcon&nbsp;MC-A5&nbsp;L1" },
        { "TRM14177.00     NONE",
          "TRM14177.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;4000ST&nbsp;L1&nbsp;Geodetic,&nbsp;Model&nbsp;14177.00" },
        { "TRM14532.00     NONE",
          "TRM14532.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;4000ST&nbsp;L1/L2&nbsp;Geodetic,&nbsp;Model&nbsp;14532.00" },
        { "TRM14532.10     NONE",
          "TRM14532.10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;4000SSE&nbsp;Kin&nbsp;L1/L2,&nbsp;Model&nbsp;14532.10" },
        { "TRM22020.00+GP  NONE",
          "TRM22020.00+GP&nbsp;&nbsp;NONE&nbsp;Geod.&nbsp;L1/L2&nbsp;compact,&nbsp;with&nbsp;groundplane,&nbsp;M" },
        { "TRM22020.00-GP  NONE",
          "TRM22020.00-GP&nbsp;&nbsp;NONE&nbsp;Geod.&nbsp;L1/L2&nbsp;compact;&nbsp;w/o&nbsp;groundplane,&nbsp;Mo" },
        { "TRM22020.02     TCWD",
          "TRM22020.02&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TCWD&nbsp;L1/L2&nbsp;w/rd&nbsp;and&nbsp;gp" },
        { "TRM23903.00     NONE",
          "TRM23903.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Permanent&nbsp;L1/L2,&nbsp;Model&nbsp;23903.00,&nbsp;cast&nbsp;pr" },
        { "TRM27947.00+GP  NONE",
          "TRM27947.00+GP&nbsp;&nbsp;NONE&nbsp;Rugged&nbsp;L1/L2&nbsp;with&nbsp;groundplane,&nbsp;Model&nbsp;279" },
        { "TRM27947.00-GP  NONE",
          "TRM27947.00-GP&nbsp;&nbsp;NONE&nbsp;Rugged&nbsp;L1/L2&nbsp;w/o&nbsp;groundplane,&nbsp;Model&nbsp;2794" },
        { "TRM29659.00     NONE",
          "TRM29659.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Trimble&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;wit" },
        { "TRM29659.00     OLGA",
          "TRM29659.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OLGA&nbsp;Trimble&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;wit" },
        { "TRM29659.00     SCIS",
          "TRM29659.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Trimble&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;wit" },
        { "TRM29659.00     SCIT",
          "TRM29659.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Trimble&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;wit" },
        { "TRM29659.00     SNOW",
          "TRM29659.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SNOW&nbsp;Trimble&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;wit" },
        { "TRM29659.00     TCWD",
          "TRM29659.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TCWD&nbsp;Trimble&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;wit" },
        { "TRM29659.00     UNAV",
          "TRM29659.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UNAV&nbsp;Trimble&nbsp;L1/L2&nbsp;Dorne&nbsp;Margolin&nbsp;element&nbsp;wit" },
        { "TRM33429.00+GP  NONE",
          "TRM33429.00+GP&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;microcentered,&nbsp;Compact&nbsp;Geodetic,&nbsp;M" },
        { "TRM33429.00-GP  NONE",
          "TRM33429.00-GP&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;microcentered,&nbsp;Compact&nbsp;Geodetic(no" },
        { "TRM33429.20+GP  NONE",
          "TRM33429.20+GP&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;microcentered,&nbsp;Compact&nbsp;Geodetic,&nbsp;M" },
        { "TRM33429.20+GP  TCWD",
          "TRM33429.20+GP&nbsp;&nbsp;TCWD&nbsp;L1/L2&nbsp;microcentered,&nbsp;Compact&nbsp;Geodetic,&nbsp;M" },
        { "TRM33429.20+GP  UNAV",
          "TRM33429.20+GP&nbsp;&nbsp;UNAV&nbsp;L1/L2&nbsp;microcentered,&nbsp;Compact&nbsp;Geodetic,&nbsp;M" },
        { "TRM36569.00+GP  NONE",
          "TRM36569.00+GP&nbsp;&nbsp;NONE&nbsp;13&nbsp;microcentered&nbsp;+GP" },
        { "TRM39105.00     NONE",
          "TRM39105.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Zephyr&nbsp;4-point&nbsp;feed&nbsp;antenna&nbsp;-&nbsp;No&nbsp;Ground" },
        { "TRM41249.00     NONE",
          "TRM41249.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Zephyr&nbsp;4-point&nbsp;feed&nbsp;antenna&nbsp;-&nbsp;Stealth&nbsp;Gr" },
        { "TRM41249.00     SCIT",
          "TRM41249.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Zephyr&nbsp;4-point&nbsp;feed&nbsp;antenna&nbsp;-&nbsp;Stealth&nbsp;Gr" },
        { "TRM41249.00     TZGD",
          "TRM41249.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TZGD&nbsp;Zephyr&nbsp;4-point&nbsp;feed&nbsp;antenna&nbsp;-&nbsp;Stealth&nbsp;Gr" },
        { "TRM41249USCG    SCIT",
          "TRM41249USCG&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Zephyr&nbsp;Geodetic&nbsp;L1/L2&nbsp;+RD&nbsp;w/&nbsp;USCG&nbsp;mount" },
        { "TRM4800         NONE",
          "TRM4800&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/enhanced&nbsp;L2&nbsp;receiver,with&nbsp;internal&nbsp;an" },
        { "TRM49700.00     NONE",
          "TRM49700.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;P/N:49700-00,&nbsp;Trimble&nbsp;Choke&nbsp;Ring" },
        { "TRM53406.00     NONE",
          "TRM53406.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Zephyr&nbsp;(L1)&nbsp;A3" },
        { "TRM55970.00     NONE",
          "TRM55970.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Zephyr&nbsp;GNSS&nbsp;II&nbsp;-&nbsp;lead-based&nbsp;solderL1/L2/" },
        { "TRM55971.00     NONE",
          "TRM55971.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Zephyr&nbsp;GNSS&nbsp;Geodetic&nbsp;II&nbsp;-&nbsp;lead-based&nbsp;sol" },
        { "TRM55971.00     SCIT",
          "TRM55971.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Zephyr&nbsp;GNSS&nbsp;Geodetic&nbsp;II&nbsp;-&nbsp;lead-based&nbsp;sol" },
        { "TRM55971.00     TZGD",
          "TRM55971.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TZGD&nbsp;Zephyr&nbsp;GNSS&nbsp;Geodetic&nbsp;II&nbsp;-&nbsp;lead-based&nbsp;sol" },
        { "TRM57970.00     NONE",
          "TRM57970.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Zephyr&nbsp;GNSS&nbsp;II&nbsp;-&nbsp;RoHS&nbsp;compliant&nbsp;solderL1" },
        { "TRM57971.00     NONE",
          "TRM57971.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Zephyr&nbsp;GNSS&nbsp;Geodetic&nbsp;II&nbsp;-&nbsp;RoHS&nbsp;compliant" },
        { "TRM5800         NONE",
          "TRM5800&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Antenna&nbsp;inside&nbsp;TRIMBLE&nbsp;5800&nbsp;and&nbsp;TRIMBLE" },
        { "TRM59800.00     NONE",
          "TRM59800.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;59" },
        { "TRM59800.00     SCIS",
          "TRM59800.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;59" },
        { "TRM59800.00     SCIT",
          "TRM59800.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;59" },
        { "TRM59800.80     NONE",
          "TRM59800.80&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;59" },
        { "TRM59800.80     SCIS",
          "TRM59800.80&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;59" },
        { "TRM59800.80     SCIT",
          "TRM59800.80&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIT&nbsp;Dorne&nbsp;Margolin&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;59" },
        { "TRM59900.00     NONE",
          "TRM59900.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;GNSS&nbsp;antenna&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;5990" },
        { "TRM59900.00     SCIS",
          "TRM59900.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCIS&nbsp;GNSS&nbsp;antenna&nbsp;with&nbsp;chokerings,&nbsp;Model&nbsp;5990" },
        { "TRMA3_L1        NONE",
          "TRMA3_L1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1&nbsp;only" },
        { "TRMR6           NONE",
          "TRMR6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;Integrated&nbsp;-&nbsp;COPIED" },
        { "TRMR8           NONE",
          "TRMR8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;receiver/antenna&nbsp;-&nbsp;COPIED" },
        { "TRMR8_GNSS      NONE",
          "TRMR8_GNSS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;GPS&nbsp;L1/L2+L2C/L5&nbsp;GLO&nbsp;L1/L2&nbsp;TR" },
        { "TRMR8_GNSS3     NONE",
          "TRMR8_GNSS3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;GPS&nbsp;L1/L2+L2C/L5&nbsp;GLO&nbsp;L1/L2&nbsp;TR" },
        { "TRM_R6          NONE",
          "TRM_R6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;L1/L2&nbsp;Integrated" },
        { "TRM_R8          NONE",
          "TRM_R8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;receiver/antenna" },
        { "TRM_R8_GNSS     NONE",
          "TRM_R8_GNSS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NONE&nbsp;Integrated&nbsp;Antenna&nbsp;(R8)&nbsp;Model&nbsp;2" },
    };


    /**
     * _more_
     *
     * @return _more_
     */
    public static ArrayList<TwoFacedObject> getAntennas() {
        if (antennas == null) {
            ArrayList<TwoFacedObject> tmp = new ArrayList<TwoFacedObject>();
            for (String[] tuple : ANTENNAS) {
                tmp.add(new TwoFacedObject(tuple[1], tuple[0]));
            }
            antennas = tmp;
        }

        return antennas;
    }



}
