convert accessibility.svg  -fuzz 50% -transparent white accessibility.png
convert activity.svg  -fuzz 50% -transparent white activity.png
convert air-vent.svg  -fuzz 50% -transparent white air-vent.png
convert airplay.svg  -fuzz 50% -transparent white airplay.png
convert alarm-check.svg  -fuzz 50% -transparent white alarm-check.png
convert alarm-clock-off.svg  -fuzz 50% -transparent white alarm-clock-off.png
convert alarm-clock.svg  -fuzz 50% -transparent white alarm-clock.png
convert alarm-minus.svg  -fuzz 50% -transparent white alarm-minus.png
convert alarm-plus.svg  -fuzz 50% -transparent white alarm-plus.png
convert album.svg  -fuzz 50% -transparent white album.png
convert alert-circle.svg  -fuzz 50% -transparent white alert-circle.png
convert alert-octagon.svg  -fuzz 50% -transparent white alert-octagon.png
convert alert-triangle.svg  -fuzz 50% -transparent white alert-triangle.png
convert align-center-horizontal.svg  -fuzz 50% -transparent white align-center-horizontal.png
convert align-center-vertical.svg  -fuzz 50% -transparent white align-center-vertical.png
convert align-center.svg  -fuzz 50% -transparent white align-center.png
convert align-end-horizontal.svg  -fuzz 50% -transparent white align-end-horizontal.png
convert align-end-vertical.svg  -fuzz 50% -transparent white align-end-vertical.png
convert align-horizontal-distribute-center.svg -fuzz 50% -transparent white     align-horizontal-distribute-center.png  
convert align-horizontal-distribute-end.svg -fuzz 50% -transparent white   align-horizontal-distribute-end.png
convert align-horizontal-distribute-start.svg -fuzz 50% -transparent white   align-horizontal-distribute-start.png
convert align-horizontal-justify-center.svg -fuzz 50% -transparent white   align-horizontal-justify-center.png
convert align-horizontal-justify-end.svg -fuzz 50% -transparent white   align-horizontal-justify-end.png
convert align-horizontal-justify-start.svg -fuzz 50% -transparent white   align-horizontal-justify-start.png
convert align-horizontal-space-around.svg -fuzz 50% -transparent white   align-horizontal-space-around.png
convert align-horizontal-space-between.svg -fuzz 50% -transparent white   align-horizontal-space-between.png
convert align-justify.svg -fuzz 50% -transparent white   align-justify.png
convert align-left.svg -fuzz 50% -transparent white   align-left.png
convert align-right.svg -fuzz 50% -transparent white   align-right.png
convert align-start-horizontal.svg -fuzz 50% -transparent white   align-start-horizontal.png
convert align-start-vertical.svg -fuzz 50% -transparent white   align-start-vertical.png
convert align-vertical-distribute-center.svg -fuzz 50% -transparent white   align-vertical-distribute-center.png
convert align-vertical-distribute-end.svg -fuzz 50% -transparent white   align-vertical-distribute-end.png
convert align-vertical-distribute-start.svg -fuzz 50% -transparent white   align-vertical-distribute-start.png
convert align-vertical-justify-center.svg -fuzz 50% -transparent white   align-vertical-justify-center.png
convert align-vertical-justify-end.svg -fuzz 50% -transparent white   align-vertical-justify-end.png
convert align-vertical-justify-start.svg -fuzz 50% -transparent white   align-vertical-justify-start.png
convert align-vertical-space-around.svg -fuzz 50% -transparent white   align-vertical-space-around.png
convert align-vertical-space-between.svg -fuzz 50% -transparent white   align-vertical-space-between.png
convert anchor.svg -fuzz 50% -transparent white   anchor.png
convert angry.svg -fuzz 50% -transparent white   angry.png
convert annoyed.svg -fuzz 50% -transparent white   annoyed.png
convert aperture.svg -fuzz 50% -transparent white   aperture.png
convert apple.svg -fuzz 50% -transparent white   apple.png
convert archive-restore.svg -fuzz 50% -transparent white   archive-restore.png
convert archive.svg -fuzz 50% -transparent white   archive.png
convert armchair.svg -fuzz 50% -transparent white   armchair.png
convert arrow-big-down.svg -fuzz 50% -transparent white   arrow-big-down.png
convert arrow-big-left.svg -fuzz 50% -transparent white   arrow-big-left.png
convert arrow-big-right.svg -fuzz 50% -transparent white   arrow-big-right.png
convert arrow-big-up.svg -fuzz 50% -transparent white   arrow-big-up.png
convert arrow-down-circle.svg -fuzz 50% -transparent white   arrow-down-circle.png
convert arrow-down-left.svg -fuzz 50% -transparent white   arrow-down-left.png
convert arrow-down-right.svg -fuzz 50% -transparent white   arrow-down-right.png
convert arrow-down.svg -fuzz 50% -transparent white   arrow-down.png
convert arrow-left-circle.svg -fuzz 50% -transparent white   arrow-left-circle.png
convert arrow-left-right.svg -fuzz 50% -transparent white   arrow-left-right.png
convert arrow-left.svg -fuzz 50% -transparent white   arrow-left.png
convert arrow-right-circle.svg -fuzz 50% -transparent white   arrow-right-circle.png
convert arrow-right.svg -fuzz 50% -transparent white   arrow-right.png
convert arrow-up-circle.svg -fuzz 50% -transparent white   arrow-up-circle.png
convert arrow-up-down.svg -fuzz 50% -transparent white   arrow-up-down.png
convert arrow-up-left.svg -fuzz 50% -transparent white   arrow-up-left.png
convert arrow-up-right.svg -fuzz 50% -transparent white   arrow-up-right.png
convert arrow-up.svg -fuzz 50% -transparent white   arrow-up.png
convert asterisk.svg -fuzz 50% -transparent white   asterisk.png
convert at-sign.svg -fuzz 50% -transparent white   at-sign.png
convert award.svg -fuzz 50% -transparent white   award.png
convert axe.svg -fuzz 50% -transparent white   axe.png
convert axis-3d.svg -fuzz 50% -transparent white   axis-3d.png
convert baby.svg -fuzz 50% -transparent white   baby.png
convert backpack.svg -fuzz 50% -transparent white   backpack.png
convert baggage-claim.svg -fuzz 50% -transparent white   baggage-claim.png
convert banana.svg -fuzz 50% -transparent white   banana.png
convert banknote.svg -fuzz 50% -transparent white   banknote.png
convert bar-chart-2.svg -fuzz 50% -transparent white   bar-chart-2.png
convert bar-chart-3.svg -fuzz 50% -transparent white   bar-chart-3.png
convert bar-chart-4.svg -fuzz 50% -transparent white   bar-chart-4.png
convert bar-chart-horizontal.svg -fuzz 50% -transparent white   bar-chart-horizontal.png
convert bar-chart.svg -fuzz 50% -transparent white   bar-chart.png
convert baseline.svg -fuzz 50% -transparent white   baseline.png
convert bath.svg -fuzz 50% -transparent white   bath.png
convert battery-charging.svg -fuzz 50% -transparent white   battery-charging.png
convert battery-full.svg -fuzz 50% -transparent white   battery-full.png
convert battery-low.svg -fuzz 50% -transparent white   battery-low.png
convert battery-medium.svg -fuzz 50% -transparent white   battery-medium.png
convert battery.svg -fuzz 50% -transparent white   battery.png
convert beaker.svg -fuzz 50% -transparent white   beaker.png
convert bean-off.svg -fuzz 50% -transparent white   bean-off.png
convert bean.svg -fuzz 50% -transparent white   bean.png
convert bed-double.svg -fuzz 50% -transparent white   bed-double.png
convert bed-single.svg -fuzz 50% -transparent white   bed-single.png
convert bed.svg -fuzz 50% -transparent white   bed.png
convert beer.svg -fuzz 50% -transparent white   beer.png
convert bell-minus.svg -fuzz 50% -transparent white   bell-minus.png
convert bell-off.svg -fuzz 50% -transparent white   bell-off.png
convert bell-plus.svg -fuzz 50% -transparent white   bell-plus.png
convert bell-ring.svg -fuzz 50% -transparent white   bell-ring.png
convert bell.svg -fuzz 50% -transparent white   bell.png
convert bike.svg -fuzz 50% -transparent white   bike.png
convert binary.svg -fuzz 50% -transparent white   binary.png
convert bitcoin.svg -fuzz 50% -transparent white   bitcoin.png
convert bluetooth-connected.svg -fuzz 50% -transparent white   bluetooth-connected.png
convert bluetooth-off.svg -fuzz 50% -transparent white   bluetooth-off.png
convert bluetooth-searching.svg -fuzz 50% -transparent white   bluetooth-searching.png
convert bluetooth.svg -fuzz 50% -transparent white   bluetooth.png
convert bold.svg -fuzz 50% -transparent white   bold.png
convert bomb.svg -fuzz 50% -transparent white   bomb.png
convert bone.svg -fuzz 50% -transparent white   bone.png
convert book-open-check.svg -fuzz 50% -transparent white   book-open-check.png
convert book-open.svg -fuzz 50% -transparent white   book-open.png
convert book.svg -fuzz 50% -transparent white   book.png
convert bookmark-minus.svg -fuzz 50% -transparent white   bookmark-minus.png
convert bookmark-plus.svg -fuzz 50% -transparent white   bookmark-plus.png
convert bookmark.svg -fuzz 50% -transparent white   bookmark.png
convert bot.svg -fuzz 50% -transparent white   bot.png
convert box-select.svg -fuzz 50% -transparent white   box-select.png
convert box.svg -fuzz 50% -transparent white   box.png
convert boxes.svg -fuzz 50% -transparent white   boxes.png
convert briefcase.svg -fuzz 50% -transparent white   briefcase.png
convert brush.svg -fuzz 50% -transparent white   brush.png
convert bug.svg -fuzz 50% -transparent white   bug.png
convert building-2.svg -fuzz 50% -transparent white   building-2.png
convert building.svg -fuzz 50% -transparent white   building.png
convert bus.svg -fuzz 50% -transparent white   bus.png
convert cake.svg -fuzz 50% -transparent white   cake.png
convert calculator.svg -fuzz 50% -transparent white   calculator.png
convert calendar-check-2.svg -fuzz 50% -transparent white   calendar-check-2.png
convert calendar-check.svg -fuzz 50% -transparent white   calendar-check.png
convert calendar-clock.svg -fuzz 50% -transparent white   calendar-clock.png
convert calendar-days.svg -fuzz 50% -transparent white   calendar-days.png
convert calendar-heart.svg -fuzz 50% -transparent white   calendar-heart.png
convert calendar-minus.svg -fuzz 50% -transparent white   calendar-minus.png
convert calendar-off.svg -fuzz 50% -transparent white   calendar-off.png
convert calendar-plus.svg -fuzz 50% -transparent white   calendar-plus.png
convert calendar-range.svg -fuzz 50% -transparent white   calendar-range.png
convert calendar-search.svg -fuzz 50% -transparent white   calendar-search.png
convert calendar-x-2.svg -fuzz 50% -transparent white   calendar-x-2.png
convert calendar-x.svg -fuzz 50% -transparent white   calendar-x.png
convert calendar.svg -fuzz 50% -transparent white   calendar.png
convert camera-off.svg -fuzz 50% -transparent white   camera-off.png
convert camera.svg -fuzz 50% -transparent white   camera.png
convert candy-off.svg -fuzz 50% -transparent white   candy-off.png
convert candy.svg -fuzz 50% -transparent white   candy.png
convert car.svg -fuzz 50% -transparent white   car.png
convert carrot.svg -fuzz 50% -transparent white   carrot.png
convert cast.svg -fuzz 50% -transparent white   cast.png
convert cat.svg -fuzz 50% -transparent white   cat.png
convert check-check.svg -fuzz 50% -transparent white   check-check.png
convert check-circle-2.svg -fuzz 50% -transparent white   check-circle-2.png
convert check-circle.svg -fuzz 50% -transparent white   check-circle.png
convert check-square.svg -fuzz 50% -transparent white   check-square.png
convert check.svg -fuzz 50% -transparent white   check.png
convert chef-hat.svg -fuzz 50% -transparent white   chef-hat.png
convert cherry.svg -fuzz 50% -transparent white   cherry.png
convert chevron-down.svg -fuzz 50% -transparent white   chevron-down.png
convert chevron-first.svg -fuzz 50% -transparent white   chevron-first.png
convert chevron-last.svg -fuzz 50% -transparent white   chevron-last.png
convert chevron-left.svg -fuzz 50% -transparent white   chevron-left.png
convert chevron-right.svg -fuzz 50% -transparent white   chevron-right.png
convert chevron-up.svg -fuzz 50% -transparent white   chevron-up.png
convert chevrons-down-up.svg -fuzz 50% -transparent white   chevrons-down-up.png
convert chevrons-down.svg -fuzz 50% -transparent white   chevrons-down.png
convert chevrons-left-right.svg -fuzz 50% -transparent white   chevrons-left-right.png
convert chevrons-left.svg -fuzz 50% -transparent white   chevrons-left.png
convert chevrons-right-left.svg -fuzz 50% -transparent white   chevrons-right-left.png
convert chevrons-right.svg -fuzz 50% -transparent white   chevrons-right.png
convert chevrons-up-down.svg -fuzz 50% -transparent white   chevrons-up-down.png
convert chevrons-up.svg -fuzz 50% -transparent white   chevrons-up.png
convert chrome.svg -fuzz 50% -transparent white   chrome.png
convert cigarette-off.svg -fuzz 50% -transparent white   cigarette-off.png
convert cigarette.svg -fuzz 50% -transparent white   cigarette.png
convert circle-dot.svg -fuzz 50% -transparent white   circle-dot.png
convert circle-ellipsis.svg -fuzz 50% -transparent white   circle-ellipsis.png
convert circle-slashed.svg -fuzz 50% -transparent white   circle-slashed.png
convert circle.svg -fuzz 50% -transparent white   circle.png
convert citrus.svg -fuzz 50% -transparent white   citrus.png
convert clapperboard.svg -fuzz 50% -transparent white   clapperboard.png
convert clipboard-check.svg -fuzz 50% -transparent white   clipboard-check.png
convert clipboard-copy.svg -fuzz 50% -transparent white   clipboard-copy.png
convert clipboard-edit.svg -fuzz 50% -transparent white   clipboard-edit.png
convert clipboard-list.svg -fuzz 50% -transparent white   clipboard-list.png
convert clipboard-signature.svg -fuzz 50% -transparent white   clipboard-signature.png
convert clipboard-type.svg -fuzz 50% -transparent white   clipboard-type.png
convert clipboard-x.svg -fuzz 50% -transparent white   clipboard-x.png
convert clipboard.svg -fuzz 50% -transparent white   clipboard.png
convert clock-1.svg -fuzz 50% -transparent white   clock-1.png
convert clock-10.svg -fuzz 50% -transparent white   clock-10.png
convert clock-11.svg -fuzz 50% -transparent white   clock-11.png
convert clock-12.svg -fuzz 50% -transparent white   clock-12.png
convert clock-2.svg -fuzz 50% -transparent white   clock-2.png
convert clock-3.svg -fuzz 50% -transparent white   clock-3.png
convert clock-4.svg -fuzz 50% -transparent white   clock-4.png
convert clock-5.svg -fuzz 50% -transparent white   clock-5.png
convert clock-6.svg -fuzz 50% -transparent white   clock-6.png
convert clock-7.svg -fuzz 50% -transparent white   clock-7.png
convert clock-8.svg -fuzz 50% -transparent white   clock-8.png
convert clock-9.svg -fuzz 50% -transparent white   clock-9.png
convert clock.svg -fuzz 50% -transparent white   clock.png
convert cloud-cog.svg -fuzz 50% -transparent white   cloud-cog.png
convert cloud-drizzle.svg -fuzz 50% -transparent white   cloud-drizzle.png
convert cloud-fog.svg -fuzz 50% -transparent white   cloud-fog.png
convert cloud-hail.svg -fuzz 50% -transparent white   cloud-hail.png
convert cloud-lightning.svg -fuzz 50% -transparent white   cloud-lightning.png
convert cloud-moon-rain.svg -fuzz 50% -transparent white   cloud-moon-rain.png
convert cloud-moon.svg -fuzz 50% -transparent white   cloud-moon.png
convert cloud-off.svg -fuzz 50% -transparent white   cloud-off.png
convert cloud-rain-wind.svg -fuzz 50% -transparent white   cloud-rain-wind.png
convert cloud-rain.svg -fuzz 50% -transparent white   cloud-rain.png
convert cloud-snow.svg -fuzz 50% -transparent white   cloud-snow.png
convert cloud-sun-rain.svg -fuzz 50% -transparent white   cloud-sun-rain.png
convert cloud-sun.svg -fuzz 50% -transparent white   cloud-sun.png
convert cloud.svg -fuzz 50% -transparent white   cloud.png
convert cloudy.svg -fuzz 50% -transparent white   cloudy.png
convert clover.svg -fuzz 50% -transparent white   clover.png
convert code-2.svg -fuzz 50% -transparent white   code-2.png
convert code.svg -fuzz 50% -transparent white   code.png
convert codepen.svg -fuzz 50% -transparent white   codepen.png
convert codesandbox.svg -fuzz 50% -transparent white   codesandbox.png
convert coffee.svg -fuzz 50% -transparent white   coffee.png
convert cog.svg -fuzz 50% -transparent white   cog.png
convert coins.svg -fuzz 50% -transparent white   coins.png
convert columns.svg -fuzz 50% -transparent white   columns.png
convert command.svg -fuzz 50% -transparent white   command.png
convert compass.svg -fuzz 50% -transparent white   compass.png
convert component.svg -fuzz 50% -transparent white   component.png
convert concierge-bell.svg -fuzz 50% -transparent white   concierge-bell.png
convert contact.svg -fuzz 50% -transparent white   contact.png
convert contrast.svg -fuzz 50% -transparent white   contrast.png
convert cookie.svg -fuzz 50% -transparent white   cookie.png
convert copy.svg -fuzz 50% -transparent white   copy.png
convert copyleft.svg -fuzz 50% -transparent white   copyleft.png
convert copyright.svg -fuzz 50% -transparent white   copyright.png
convert corner-down-left.svg -fuzz 50% -transparent white   corner-down-left.png
convert corner-down-right.svg -fuzz 50% -transparent white   corner-down-right.png
convert corner-left-down.svg -fuzz 50% -transparent white   corner-left-down.png
convert corner-left-up.svg -fuzz 50% -transparent white   corner-left-up.png
convert corner-right-down.svg -fuzz 50% -transparent white   corner-right-down.png
convert corner-right-up.svg -fuzz 50% -transparent white   corner-right-up.png
convert corner-up-left.svg -fuzz 50% -transparent white   corner-up-left.png
convert corner-up-right.svg -fuzz 50% -transparent white   corner-up-right.png
convert cpu.svg -fuzz 50% -transparent white   cpu.png
convert credit-card.svg -fuzz 50% -transparent white   credit-card.png
convert croissant.svg -fuzz 50% -transparent white   croissant.png
convert crop.svg -fuzz 50% -transparent white   crop.png
convert cross.svg -fuzz 50% -transparent white   cross.png
convert crosshair.svg -fuzz 50% -transparent white   crosshair.png
convert crown.svg -fuzz 50% -transparent white   crown.png
convert cup-soda.svg -fuzz 50% -transparent white   cup-soda.png
convert curly-braces.svg -fuzz 50% -transparent white   curly-braces.png
convert currency.svg -fuzz 50% -transparent white   currency.png
convert database.svg -fuzz 50% -transparent white   database.png
convert delete.svg -fuzz 50% -transparent white   delete.png
convert diamond.svg -fuzz 50% -transparent white   diamond.png
convert dice-1.svg -fuzz 50% -transparent white   dice-1.png
convert dice-2.svg -fuzz 50% -transparent white   dice-2.png
convert dice-3.svg -fuzz 50% -transparent white   dice-3.png
convert dice-4.svg -fuzz 50% -transparent white   dice-4.png
convert dice-5.svg -fuzz 50% -transparent white   dice-5.png
convert dice-6.svg -fuzz 50% -transparent white   dice-6.png
convert dices.svg -fuzz 50% -transparent white   dices.png
convert diff.svg -fuzz 50% -transparent white   diff.png
convert disc.svg -fuzz 50% -transparent white   disc.png
convert divide-circle.svg -fuzz 50% -transparent white   divide-circle.png
convert divide-square.svg -fuzz 50% -transparent white   divide-square.png
convert divide.svg -fuzz 50% -transparent white   divide.png
convert dna-off.svg -fuzz 50% -transparent white   dna-off.png
convert dna.svg -fuzz 50% -transparent white   dna.png
convert dog.svg -fuzz 50% -transparent white   dog.png
convert dollar-sign.svg -fuzz 50% -transparent white   dollar-sign.png
convert download-cloud.svg -fuzz 50% -transparent white   download-cloud.png
convert download.svg -fuzz 50% -transparent white   download.png
convert dribbble.svg -fuzz 50% -transparent white   dribbble.png
convert droplet.svg -fuzz 50% -transparent white   droplet.png
convert droplets.svg -fuzz 50% -transparent white   droplets.png
convert drumstick.svg -fuzz 50% -transparent white   drumstick.png
convert dumbbell.svg -fuzz 50% -transparent white   dumbbell.png
convert ear-off.svg -fuzz 50% -transparent white   ear-off.png
convert ear.svg -fuzz 50% -transparent white   ear.png
convert edit-2.svg -fuzz 50% -transparent white   edit-2.png
convert edit-3.svg -fuzz 50% -transparent white   edit-3.png
convert edit.svg -fuzz 50% -transparent white   edit.png
convert egg-fried.svg -fuzz 50% -transparent white   egg-fried.png
convert egg-off.svg -fuzz 50% -transparent white   egg-off.png
convert egg.svg -fuzz 50% -transparent white   egg.png
convert equal-not.svg -fuzz 50% -transparent white   equal-not.png
convert equal.svg -fuzz 50% -transparent white   equal.png
convert eraser.svg -fuzz 50% -transparent white   eraser.png
convert euro.svg -fuzz 50% -transparent white   euro.png
convert expand.svg -fuzz 50% -transparent white   expand.png
convert external-link.svg -fuzz 50% -transparent white   external-link.png
convert eye-off.svg -fuzz 50% -transparent white   eye-off.png
convert eye.svg -fuzz 50% -transparent white   eye.png
convert facebook.svg -fuzz 50% -transparent white   facebook.png
convert factory.svg -fuzz 50% -transparent white   factory.png
convert fan.svg -fuzz 50% -transparent white   fan.png
convert fast-forward.svg -fuzz 50% -transparent white   fast-forward.png
convert feather.svg -fuzz 50% -transparent white   feather.png
convert figma.svg -fuzz 50% -transparent white   figma.png
convert file-archive.svg -fuzz 50% -transparent white   file-archive.png
convert file-audio-2.svg -fuzz 50% -transparent white   file-audio-2.png
convert file-audio.svg -fuzz 50% -transparent white   file-audio.png
convert file-axis-3d.svg -fuzz 50% -transparent white   file-axis-3d.png
convert file-badge-2.svg -fuzz 50% -transparent white   file-badge-2.png
convert file-badge.svg -fuzz 50% -transparent white   file-badge.png
convert file-bar-chart-2.svg -fuzz 50% -transparent white   file-bar-chart-2.png
convert file-bar-chart.svg -fuzz 50% -transparent white   file-bar-chart.png
convert file-box.svg -fuzz 50% -transparent white   file-box.png
convert file-check-2.svg -fuzz 50% -transparent white   file-check-2.png
convert file-check.svg -fuzz 50% -transparent white   file-check.png
convert file-clock.svg -fuzz 50% -transparent white   file-clock.png
convert file-code.svg -fuzz 50% -transparent white   file-code.png
convert file-cog-2.svg -fuzz 50% -transparent white   file-cog-2.png
convert file-cog.svg -fuzz 50% -transparent white   file-cog.png
convert file-diff.svg -fuzz 50% -transparent white   file-diff.png
convert file-digit.svg -fuzz 50% -transparent white   file-digit.png
convert file-down.svg -fuzz 50% -transparent white   file-down.png
convert file-edit.svg -fuzz 50% -transparent white   file-edit.png
convert file-heart.svg -fuzz 50% -transparent white   file-heart.png
convert file-image.svg -fuzz 50% -transparent white   file-image.png
convert file-input.svg -fuzz 50% -transparent white   file-input.png
convert file-json-2.svg -fuzz 50% -transparent white   file-json-2.png
convert file-json.svg -fuzz 50% -transparent white   file-json.png
convert file-key-2.svg -fuzz 50% -transparent white   file-key-2.png
convert file-key.svg -fuzz 50% -transparent white   file-key.png
convert file-line-chart.svg -fuzz 50% -transparent white   file-line-chart.png
convert file-lock-2.svg -fuzz 50% -transparent white   file-lock-2.png
convert file-lock.svg -fuzz 50% -transparent white   file-lock.png
convert file-minus-2.svg -fuzz 50% -transparent white   file-minus-2.png
convert file-minus.svg -fuzz 50% -transparent white   file-minus.png
convert file-output.svg -fuzz 50% -transparent white   file-output.png
convert file-pie-chart.svg -fuzz 50% -transparent white   file-pie-chart.png
convert file-plus-2.svg -fuzz 50% -transparent white   file-plus-2.png
convert file-plus.svg -fuzz 50% -transparent white   file-plus.png
convert file-question.svg -fuzz 50% -transparent white   file-question.png
convert file-scan.svg -fuzz 50% -transparent white   file-scan.png
convert file-search-2.svg -fuzz 50% -transparent white   file-search-2.png
convert file-search.svg -fuzz 50% -transparent white   file-search.png
convert file-signature.svg -fuzz 50% -transparent white   file-signature.png
convert file-spreadsheet.svg -fuzz 50% -transparent white   file-spreadsheet.png
convert file-symlink.svg -fuzz 50% -transparent white   file-symlink.png
convert file-terminal.svg -fuzz 50% -transparent white   file-terminal.png
convert file-text.svg -fuzz 50% -transparent white   file-text.png
convert file-type-2.svg -fuzz 50% -transparent white   file-type-2.png
convert file-type.svg -fuzz 50% -transparent white   file-type.png
convert file-up.svg -fuzz 50% -transparent white   file-up.png
convert file-video-2.svg -fuzz 50% -transparent white   file-video-2.png
convert file-video.svg -fuzz 50% -transparent white   file-video.png
convert file-volume-2.svg -fuzz 50% -transparent white   file-volume-2.png
convert file-volume.svg -fuzz 50% -transparent white   file-volume.png
convert file-warning.svg -fuzz 50% -transparent white   file-warning.png
convert file-x-2.svg -fuzz 50% -transparent white   file-x-2.png
convert file-x.svg -fuzz 50% -transparent white   file-x.png
convert file.svg -fuzz 50% -transparent white   file.png
convert files.svg -fuzz 50% -transparent white   files.png
convert film.svg -fuzz 50% -transparent white   film.png
convert filter.svg -fuzz 50% -transparent white   filter.png
convert fingerprint.svg -fuzz 50% -transparent white   fingerprint.png
convert flag-off.svg -fuzz 50% -transparent white   flag-off.png
convert flag-triangle-left.svg -fuzz 50% -transparent white   flag-triangle-left.png
convert flag-triangle-right.svg -fuzz 50% -transparent white   flag-triangle-right.png
convert flag.svg -fuzz 50% -transparent white   flag.png
convert flame.svg -fuzz 50% -transparent white   flame.png
convert flashlight-off.svg -fuzz 50% -transparent white   flashlight-off.png
convert flashlight.svg -fuzz 50% -transparent white   flashlight.png
convert flask-conical-off.svg -fuzz 50% -transparent white   flask-conical-off.png
convert flask-conical.svg -fuzz 50% -transparent white   flask-conical.png
convert flask-round.svg -fuzz 50% -transparent white   flask-round.png
convert flip-horizontal-2.svg -fuzz 50% -transparent white   flip-horizontal-2.png
convert flip-horizontal.svg -fuzz 50% -transparent white   flip-horizontal.png
convert flip-vertical-2.svg -fuzz 50% -transparent white   flip-vertical-2.png
convert flip-vertical.svg -fuzz 50% -transparent white   flip-vertical.png
convert flower-2.svg -fuzz 50% -transparent white   flower-2.png
convert flower.svg -fuzz 50% -transparent white   flower.png
convert focus.svg -fuzz 50% -transparent white   focus.png
convert folder-archive.svg -fuzz 50% -transparent white   folder-archive.png
convert folder-check.svg -fuzz 50% -transparent white   folder-check.png
convert folder-clock.svg -fuzz 50% -transparent white   folder-clock.png
convert folder-closed.svg -fuzz 50% -transparent white   folder-closed.png
convert folder-cog-2.svg -fuzz 50% -transparent white   folder-cog-2.png
convert folder-cog.svg -fuzz 50% -transparent white   folder-cog.png
convert folder-down.svg -fuzz 50% -transparent white   folder-down.png
convert folder-edit.svg -fuzz 50% -transparent white   folder-edit.png
convert folder-heart.svg -fuzz 50% -transparent white   folder-heart.png
convert folder-input.svg -fuzz 50% -transparent white   folder-input.png
convert folder-key.svg -fuzz 50% -transparent white   folder-key.png
convert folder-lock.svg -fuzz 50% -transparent white   folder-lock.png
convert folder-minus.svg -fuzz 50% -transparent white   folder-minus.png
convert folder-open.svg -fuzz 50% -transparent white   folder-open.png
convert folder-output.svg -fuzz 50% -transparent white   folder-output.png
convert folder-plus.svg -fuzz 50% -transparent white   folder-plus.png
convert folder-search-2.svg -fuzz 50% -transparent white   folder-search-2.png
convert folder-search.svg -fuzz 50% -transparent white   folder-search.png
convert folder-symlink.svg -fuzz 50% -transparent white   folder-symlink.png
convert folder-tree.svg -fuzz 50% -transparent white   folder-tree.png
convert folder-up.svg -fuzz 50% -transparent white   folder-up.png
convert folder-x.svg -fuzz 50% -transparent white   folder-x.png
convert folder.svg -fuzz 50% -transparent white   folder.png
convert folders.svg -fuzz 50% -transparent white   folders.png
convert form-input.svg -fuzz 50% -transparent white   form-input.png
convert forward.svg -fuzz 50% -transparent white   forward.png
convert frame.svg -fuzz 50% -transparent white   frame.png
convert framer.svg -fuzz 50% -transparent white   framer.png
convert frown.svg -fuzz 50% -transparent white   frown.png
convert fuel.svg -fuzz 50% -transparent white   fuel.png
convert function-square.svg -fuzz 50% -transparent white   function-square.png
convert gamepad-2.svg -fuzz 50% -transparent white   gamepad-2.png
convert gamepad.svg -fuzz 50% -transparent white   gamepad.png
convert gauge.svg -fuzz 50% -transparent white   gauge.png
convert gavel.svg -fuzz 50% -transparent white   gavel.png
convert gem.svg -fuzz 50% -transparent white   gem.png
convert ghost.svg -fuzz 50% -transparent white   ghost.png
convert gift.svg -fuzz 50% -transparent white   gift.png
convert git-branch-plus.svg -fuzz 50% -transparent white   git-branch-plus.png
convert git-branch.svg -fuzz 50% -transparent white   git-branch.png
convert git-commit.svg -fuzz 50% -transparent white   git-commit.png
convert git-compare.svg -fuzz 50% -transparent white   git-compare.png
convert git-fork.svg -fuzz 50% -transparent white   git-fork.png
convert git-merge.svg -fuzz 50% -transparent white   git-merge.png
convert git-pull-request-closed.svg -fuzz 50% -transparent white   git-pull-request-closed.png
convert git-pull-request-draft.svg -fuzz 50% -transparent white   git-pull-request-draft.png
convert git-pull-request.svg -fuzz 50% -transparent white   git-pull-request.png
convert github.svg -fuzz 50% -transparent white   github.png
convert gitlab.svg -fuzz 50% -transparent white   gitlab.png
convert glass-water.svg -fuzz 50% -transparent white   glass-water.png
convert glasses.svg -fuzz 50% -transparent white   glasses.png
convert globe-2.svg -fuzz 50% -transparent white   globe-2.png
convert globe.svg -fuzz 50% -transparent white   globe.png
convert grab.svg -fuzz 50% -transparent white   grab.png
convert graduation-cap.svg -fuzz 50% -transparent white   graduation-cap.png
convert grape.svg -fuzz 50% -transparent white   grape.png
convert grid.svg -fuzz 50% -transparent white   grid.png
convert grip-horizontal.svg -fuzz 50% -transparent white   grip-horizontal.png
convert grip-vertical.svg -fuzz 50% -transparent white   grip-vertical.png
convert hammer.svg -fuzz 50% -transparent white   hammer.png
convert hand-metal.svg -fuzz 50% -transparent white   hand-metal.png
convert hand.svg -fuzz 50% -transparent white   hand.png
convert hard-drive.svg -fuzz 50% -transparent white   hard-drive.png
convert hard-hat.svg -fuzz 50% -transparent white   hard-hat.png
convert hash.svg -fuzz 50% -transparent white   hash.png
convert haze.svg -fuzz 50% -transparent white   haze.png
convert heading-1.svg -fuzz 50% -transparent white   heading-1.png
convert heading-2.svg -fuzz 50% -transparent white   heading-2.png
convert heading-3.svg -fuzz 50% -transparent white   heading-3.png
convert heading-4.svg -fuzz 50% -transparent white   heading-4.png
convert heading-5.svg -fuzz 50% -transparent white   heading-5.png
convert heading-6.svg -fuzz 50% -transparent white   heading-6.png
convert heading.svg -fuzz 50% -transparent white   heading.png
convert headphones.svg -fuzz 50% -transparent white   headphones.png
convert heart-crack.svg -fuzz 50% -transparent white   heart-crack.png
convert heart-handshake.svg -fuzz 50% -transparent white   heart-handshake.png
convert heart-off.svg -fuzz 50% -transparent white   heart-off.png
convert heart-pulse.svg -fuzz 50% -transparent white   heart-pulse.png
convert heart.svg -fuzz 50% -transparent white   heart.png
convert help-circle.svg -fuzz 50% -transparent white   help-circle.png
convert hexagon.svg -fuzz 50% -transparent white   hexagon.png
convert highlighter.svg -fuzz 50% -transparent white   highlighter.png
convert history.svg -fuzz 50% -transparent white   history.png
convert home.svg -fuzz 50% -transparent white   home.png
convert hop-off.svg -fuzz 50% -transparent white   hop-off.png
convert hop.svg -fuzz 50% -transparent white   hop.png
convert hourglass.svg -fuzz 50% -transparent white   hourglass.png
convert ice-cream.svg -fuzz 50% -transparent white   ice-cream.png
convert image-minus.svg -fuzz 50% -transparent white   image-minus.png
convert image-off.svg -fuzz 50% -transparent white   image-off.png
convert image-plus.svg -fuzz 50% -transparent white   image-plus.png
convert image.svg -fuzz 50% -transparent white   image.png
convert import.svg -fuzz 50% -transparent white   import.png
convert inbox.svg -fuzz 50% -transparent white   inbox.png
convert indent.svg -fuzz 50% -transparent white   indent.png
convert indian-rupee.svg -fuzz 50% -transparent white   indian-rupee.png
convert infinity.svg -fuzz 50% -transparent white   infinity.png
convert info.svg -fuzz 50% -transparent white   info.png
convert inspect.svg -fuzz 50% -transparent white   inspect.png
convert instagram.svg -fuzz 50% -transparent white   instagram.png
convert italic.svg -fuzz 50% -transparent white   italic.png
convert japanese-yen.svg -fuzz 50% -transparent white   japanese-yen.png
convert joystick.svg -fuzz 50% -transparent white   joystick.png
convert key.svg -fuzz 50% -transparent white   key.png
convert keyboard.svg -fuzz 50% -transparent white   keyboard.png
convert lamp-ceiling.svg -fuzz 50% -transparent white   lamp-ceiling.png
convert lamp-desk.svg -fuzz 50% -transparent white   lamp-desk.png
convert lamp-floor.svg -fuzz 50% -transparent white   lamp-floor.png
convert lamp-wall-down.svg -fuzz 50% -transparent white   lamp-wall-down.png
convert lamp-wall-up.svg -fuzz 50% -transparent white   lamp-wall-up.png
convert lamp.svg -fuzz 50% -transparent white   lamp.png
convert landmark.svg -fuzz 50% -transparent white   landmark.png
convert languages.svg -fuzz 50% -transparent white   languages.png
convert laptop-2.svg -fuzz 50% -transparent white   laptop-2.png
convert laptop.svg -fuzz 50% -transparent white   laptop.png
convert lasso-select.svg -fuzz 50% -transparent white   lasso-select.png
convert lasso.svg -fuzz 50% -transparent white   lasso.png
convert laugh.svg -fuzz 50% -transparent white   laugh.png
convert layers.svg -fuzz 50% -transparent white   layers.png
convert layout-dashboard.svg -fuzz 50% -transparent white   layout-dashboard.png
convert layout-grid.svg -fuzz 50% -transparent white   layout-grid.png
convert layout-list.svg -fuzz 50% -transparent white   layout-list.png
convert layout-template.svg -fuzz 50% -transparent white   layout-template.png
convert layout.svg -fuzz 50% -transparent white   layout.png
convert leaf.svg -fuzz 50% -transparent white   leaf.png
convert library.svg -fuzz 50% -transparent white   library.png
convert life-buoy.svg -fuzz 50% -transparent white   life-buoy.png
convert lightbulb-off.svg -fuzz 50% -transparent white   lightbulb-off.png
convert lightbulb.svg -fuzz 50% -transparent white   lightbulb.png
convert line-chart.svg -fuzz 50% -transparent white   line-chart.png
convert link-2-off.svg -fuzz 50% -transparent white   link-2-off.png
convert link-2.svg -fuzz 50% -transparent white   link-2.png
convert link.svg -fuzz 50% -transparent white   link.png
convert linkedin.svg -fuzz 50% -transparent white   linkedin.png
convert list-checks.svg -fuzz 50% -transparent white   list-checks.png
convert list-end.svg -fuzz 50% -transparent white   list-end.png
convert list-minus.svg -fuzz 50% -transparent white   list-minus.png
convert list-music.svg -fuzz 50% -transparent white   list-music.png
convert list-ordered.svg -fuzz 50% -transparent white   list-ordered.png
convert list-plus.svg -fuzz 50% -transparent white   list-plus.png
convert list-start.svg -fuzz 50% -transparent white   list-start.png
convert list-video.svg -fuzz 50% -transparent white   list-video.png
convert list-x.svg -fuzz 50% -transparent white   list-x.png
convert list.svg -fuzz 50% -transparent white   list.png
convert loader-2.svg -fuzz 50% -transparent white   loader-2.png
convert loader.svg -fuzz 50% -transparent white   loader.png
convert locate-fixed.svg -fuzz 50% -transparent white   locate-fixed.png
convert locate-off.svg -fuzz 50% -transparent white   locate-off.png
convert locate.svg -fuzz 50% -transparent white   locate.png
convert lock.svg -fuzz 50% -transparent white   lock.png
convert log-in.svg -fuzz 50% -transparent white   log-in.png
convert log-out.svg -fuzz 50% -transparent white   log-out.png
convert luggage.svg -fuzz 50% -transparent white   luggage.png
convert magnet.svg -fuzz 50% -transparent white   magnet.png
convert mail-check.svg -fuzz 50% -transparent white   mail-check.png
convert mail-minus.svg -fuzz 50% -transparent white   mail-minus.png
convert mail-open.svg -fuzz 50% -transparent white   mail-open.png
convert mail-plus.svg -fuzz 50% -transparent white   mail-plus.png
convert mail-question.svg -fuzz 50% -transparent white   mail-question.png
convert mail-search.svg -fuzz 50% -transparent white   mail-search.png
convert mail-warning.svg -fuzz 50% -transparent white   mail-warning.png
convert mail-x.svg -fuzz 50% -transparent white   mail-x.png
convert mail.svg -fuzz 50% -transparent white   mail.png
convert mails.svg -fuzz 50% -transparent white   mails.png
convert map-pin-off.svg -fuzz 50% -transparent white   map-pin-off.png
convert map-pin.svg -fuzz 50% -transparent white   map-pin.png
convert map.svg -fuzz 50% -transparent white   map.png
convert martini.svg -fuzz 50% -transparent white   martini.png
convert maximize-2.svg -fuzz 50% -transparent white   maximize-2.png
convert maximize.svg -fuzz 50% -transparent white   maximize.png
convert medal.svg -fuzz 50% -transparent white   medal.png
convert megaphone-off.svg -fuzz 50% -transparent white   megaphone-off.png
convert megaphone.svg -fuzz 50% -transparent white   megaphone.png
convert meh.svg -fuzz 50% -transparent white   meh.png
convert menu.svg -fuzz 50% -transparent white   menu.png
convert message-circle.svg -fuzz 50% -transparent white   message-circle.png
convert message-square.svg -fuzz 50% -transparent white   message-square.png
convert mic-2.svg -fuzz 50% -transparent white   mic-2.png
convert mic-off.svg -fuzz 50% -transparent white   mic-off.png
convert mic.svg -fuzz 50% -transparent white   mic.png
convert microscope.svg -fuzz 50% -transparent white   microscope.png
convert microwave.svg -fuzz 50% -transparent white   microwave.png
convert milestone.svg -fuzz 50% -transparent white   milestone.png
convert milk-off.svg -fuzz 50% -transparent white   milk-off.png
convert milk.svg -fuzz 50% -transparent white   milk.png
convert minimize-2.svg -fuzz 50% -transparent white   minimize-2.png
convert minimize.svg -fuzz 50% -transparent white   minimize.png
convert minus-circle.svg -fuzz 50% -transparent white   minus-circle.png
convert minus-square.svg -fuzz 50% -transparent white   minus-square.png
convert minus.svg -fuzz 50% -transparent white   minus.png
convert monitor-off.svg -fuzz 50% -transparent white   monitor-off.png
convert monitor-smartphone.svg -fuzz 50% -transparent white   monitor-smartphone.png
convert monitor-speaker.svg -fuzz 50% -transparent white   monitor-speaker.png
convert monitor.svg -fuzz 50% -transparent white   monitor.png
convert moon.svg -fuzz 50% -transparent white   moon.png
convert more-horizontal.svg -fuzz 50% -transparent white   more-horizontal.png
convert more-vertical.svg -fuzz 50% -transparent white   more-vertical.png
convert mountain-snow.svg -fuzz 50% -transparent white   mountain-snow.png
convert mountain.svg -fuzz 50% -transparent white   mountain.png
convert mouse-pointer-2.svg -fuzz 50% -transparent white   mouse-pointer-2.png
convert mouse-pointer-click.svg -fuzz 50% -transparent white   mouse-pointer-click.png
convert mouse-pointer.svg -fuzz 50% -transparent white   mouse-pointer.png
convert mouse.svg -fuzz 50% -transparent white   mouse.png
convert move-3d.svg -fuzz 50% -transparent white   move-3d.png
convert move-diagonal-2.svg -fuzz 50% -transparent white   move-diagonal-2.png
convert move-diagonal.svg -fuzz 50% -transparent white   move-diagonal.png
convert move-horizontal.svg -fuzz 50% -transparent white   move-horizontal.png
convert move-vertical.svg -fuzz 50% -transparent white   move-vertical.png
convert move.svg -fuzz 50% -transparent white   move.png
convert music-2.svg -fuzz 50% -transparent white   music-2.png
convert music-3.svg -fuzz 50% -transparent white   music-3.png
convert music-4.svg -fuzz 50% -transparent white   music-4.png
convert music.svg -fuzz 50% -transparent white   music.png
convert navigation-2-off.svg -fuzz 50% -transparent white   navigation-2-off.png
convert navigation-2.svg -fuzz 50% -transparent white   navigation-2.png
convert navigation-off.svg -fuzz 50% -transparent white   navigation-off.png
convert navigation.svg -fuzz 50% -transparent white   navigation.png
convert network.svg -fuzz 50% -transparent white   network.png
convert newspaper.svg -fuzz 50% -transparent white   newspaper.png
convert nut-off.svg -fuzz 50% -transparent white   nut-off.png
convert nut.svg -fuzz 50% -transparent white   nut.png
convert octagon.svg -fuzz 50% -transparent white   octagon.png
convert option.svg -fuzz 50% -transparent white   option.png
convert outdent.svg -fuzz 50% -transparent white   outdent.png
convert package-2.svg -fuzz 50% -transparent white   package-2.png
convert package-check.svg -fuzz 50% -transparent white   package-check.png
convert package-minus.svg -fuzz 50% -transparent white   package-minus.png
convert package-open.svg -fuzz 50% -transparent white   package-open.png
convert package-plus.svg -fuzz 50% -transparent white   package-plus.png
convert package-search.svg -fuzz 50% -transparent white   package-search.png
convert package-x.svg -fuzz 50% -transparent white   package-x.png
convert package.svg -fuzz 50% -transparent white   package.png
convert paint-bucket.svg -fuzz 50% -transparent white   paint-bucket.png
convert paintbrush-2.svg -fuzz 50% -transparent white   paintbrush-2.png
convert paintbrush.svg -fuzz 50% -transparent white   paintbrush.png
convert palette.svg -fuzz 50% -transparent white   palette.png
convert palmtree.svg -fuzz 50% -transparent white   palmtree.png
convert paperclip.svg -fuzz 50% -transparent white   paperclip.png
convert party-popper.svg -fuzz 50% -transparent white   party-popper.png
convert pause-circle.svg -fuzz 50% -transparent white   pause-circle.png
convert pause-octagon.svg -fuzz 50% -transparent white   pause-octagon.png
convert pause.svg -fuzz 50% -transparent white   pause.png
convert pen-tool.svg -fuzz 50% -transparent white   pen-tool.png
convert pencil.svg -fuzz 50% -transparent white   pencil.png
convert percent.svg -fuzz 50% -transparent white   percent.png
convert person-standing.svg -fuzz 50% -transparent white   person-standing.png
convert phone-call.svg -fuzz 50% -transparent white   phone-call.png
convert phone-forwarded.svg -fuzz 50% -transparent white   phone-forwarded.png
convert phone-incoming.svg -fuzz 50% -transparent white   phone-incoming.png
convert phone-missed.svg -fuzz 50% -transparent white   phone-missed.png
convert phone-off.svg -fuzz 50% -transparent white   phone-off.png
convert phone-outgoing.svg -fuzz 50% -transparent white   phone-outgoing.png
convert phone.svg -fuzz 50% -transparent white   phone.png
convert pie-chart.svg -fuzz 50% -transparent white   pie-chart.png
convert piggy-bank.svg -fuzz 50% -transparent white   piggy-bank.png
convert pilcrow.svg -fuzz 50% -transparent white   pilcrow.png
convert pin-off.svg -fuzz 50% -transparent white   pin-off.png
convert pin.svg -fuzz 50% -transparent white   pin.png
convert pipette.svg -fuzz 50% -transparent white   pipette.png
convert pizza.svg -fuzz 50% -transparent white   pizza.png
convert plane.svg -fuzz 50% -transparent white   plane.png
convert play-circle.svg -fuzz 50% -transparent white   play-circle.png
convert play.svg -fuzz 50% -transparent white   play.png
convert plug-2.svg -fuzz 50% -transparent white   plug-2.png
convert plug-zap.svg -fuzz 50% -transparent white   plug-zap.png
convert plug.svg -fuzz 50% -transparent white   plug.png
convert plus-circle.svg -fuzz 50% -transparent white   plus-circle.png
convert plus-square.svg -fuzz 50% -transparent white   plus-square.png
convert plus.svg -fuzz 50% -transparent white   plus.png
convert pocket.svg -fuzz 50% -transparent white   pocket.png
convert podcast.svg -fuzz 50% -transparent white   podcast.png
convert pointer.svg -fuzz 50% -transparent white   pointer.png
convert pound-sterling.svg -fuzz 50% -transparent white   pound-sterling.png
convert power-off.svg -fuzz 50% -transparent white   power-off.png
convert power.svg -fuzz 50% -transparent white   power.png
convert printer.svg -fuzz 50% -transparent white   printer.png
convert puzzle.svg -fuzz 50% -transparent white   puzzle.png
convert qr-code.svg -fuzz 50% -transparent white   qr-code.png
convert quote.svg -fuzz 50% -transparent white   quote.png
convert radio-receiver.svg -fuzz 50% -transparent white   radio-receiver.png
convert radio.svg -fuzz 50% -transparent white   radio.png
convert rectangle-horizontal.svg -fuzz 50% -transparent white   rectangle-horizontal.png
convert rectangle-vertical.svg -fuzz 50% -transparent white   rectangle-vertical.png
convert recycle.svg -fuzz 50% -transparent white   recycle.png
convert redo-2.svg -fuzz 50% -transparent white   redo-2.png
convert redo.svg -fuzz 50% -transparent white   redo.png
convert refresh-ccw.svg -fuzz 50% -transparent white   refresh-ccw.png
convert refresh-cw.svg -fuzz 50% -transparent white   refresh-cw.png
convert refrigerator.svg -fuzz 50% -transparent white   refrigerator.png
convert regex.svg -fuzz 50% -transparent white   regex.png
convert repeat-1.svg -fuzz 50% -transparent white   repeat-1.png
convert repeat.svg -fuzz 50% -transparent white   repeat.png
convert reply-all.svg -fuzz 50% -transparent white   reply-all.png
convert reply.svg -fuzz 50% -transparent white   reply.png
convert rewind.svg -fuzz 50% -transparent white   rewind.png
convert rocket.svg -fuzz 50% -transparent white   rocket.png
convert rocking-chair.svg -fuzz 50% -transparent white   rocking-chair.png
convert rotate-3d.svg -fuzz 50% -transparent white   rotate-3d.png
convert rotate-ccw.svg -fuzz 50% -transparent white   rotate-ccw.png
convert rotate-cw.svg -fuzz 50% -transparent white   rotate-cw.png
convert rss.svg -fuzz 50% -transparent white   rss.png
convert ruler.svg -fuzz 50% -transparent white   ruler.png
convert russian-ruble.svg -fuzz 50% -transparent white   russian-ruble.png
convert sailboat.svg -fuzz 50% -transparent white   sailboat.png
convert save.svg -fuzz 50% -transparent white   save.png
convert scale-3d.svg -fuzz 50% -transparent white   scale-3d.png
convert scale.svg -fuzz 50% -transparent white   scale.png
convert scaling.svg -fuzz 50% -transparent white   scaling.png
convert scan-face.svg -fuzz 50% -transparent white   scan-face.png
convert scan-line.svg -fuzz 50% -transparent white   scan-line.png
convert scan.svg -fuzz 50% -transparent white   scan.png
convert scissors.svg -fuzz 50% -transparent white   scissors.png
convert screen-share-off.svg -fuzz 50% -transparent white   screen-share-off.png
convert screen-share.svg -fuzz 50% -transparent white   screen-share.png
convert scroll.svg -fuzz 50% -transparent white   scroll.png
convert search.svg -fuzz 50% -transparent white   search.png
convert send.svg -fuzz 50% -transparent white   send.png
convert separator-horizontal.svg -fuzz 50% -transparent white   separator-horizontal.png
convert separator-vertical.svg -fuzz 50% -transparent white   separator-vertical.png
convert server-cog.svg -fuzz 50% -transparent white   server-cog.png
convert server-crash.svg -fuzz 50% -transparent white   server-crash.png
convert server-off.svg -fuzz 50% -transparent white   server-off.png
convert server.svg -fuzz 50% -transparent white   server.png
convert settings-2.svg -fuzz 50% -transparent white   settings-2.png
convert settings.svg -fuzz 50% -transparent white   settings.png
convert share-2.svg -fuzz 50% -transparent white   share-2.png
convert share.svg -fuzz 50% -transparent white   share.png
convert sheet.svg -fuzz 50% -transparent white   sheet.png
convert shield-alert.svg -fuzz 50% -transparent white   shield-alert.png
convert shield-check.svg -fuzz 50% -transparent white   shield-check.png
convert shield-close.svg -fuzz 50% -transparent white   shield-close.png
convert shield-off.svg -fuzz 50% -transparent white   shield-off.png
convert shield.svg -fuzz 50% -transparent white   shield.png
convert shirt.svg -fuzz 50% -transparent white   shirt.png
convert shopping-bag.svg -fuzz 50% -transparent white   shopping-bag.png
convert shopping-cart.svg -fuzz 50% -transparent white   shopping-cart.png
convert shovel.svg -fuzz 50% -transparent white   shovel.png
convert shower-head.svg -fuzz 50% -transparent white   shower-head.png
convert shrink.svg -fuzz 50% -transparent white   shrink.png
convert shrub.svg -fuzz 50% -transparent white   shrub.png
convert shuffle.svg -fuzz 50% -transparent white   shuffle.png
convert sidebar-close.svg -fuzz 50% -transparent white   sidebar-close.png
convert sidebar-open.svg -fuzz 50% -transparent white   sidebar-open.png
convert sidebar.svg -fuzz 50% -transparent white   sidebar.png
convert sigma.svg -fuzz 50% -transparent white   sigma.png
convert signal-high.svg -fuzz 50% -transparent white   signal-high.png
convert signal-low.svg -fuzz 50% -transparent white   signal-low.png
convert signal-medium.svg -fuzz 50% -transparent white   signal-medium.png
convert signal-zero.svg -fuzz 50% -transparent white   signal-zero.png
convert signal.svg -fuzz 50% -transparent white   signal.png
convert siren.svg -fuzz 50% -transparent white   siren.png
convert skip-back.svg -fuzz 50% -transparent white   skip-back.png
convert skip-forward.svg -fuzz 50% -transparent white   skip-forward.png
convert skull.svg -fuzz 50% -transparent white   skull.png
convert slack.svg -fuzz 50% -transparent white   slack.png
convert slash.svg -fuzz 50% -transparent white   slash.png
convert slice.svg -fuzz 50% -transparent white   slice.png
convert sliders-horizontal.svg -fuzz 50% -transparent white   sliders-horizontal.png
convert sliders.svg -fuzz 50% -transparent white   sliders.png
convert smartphone-charging.svg -fuzz 50% -transparent white   smartphone-charging.png
convert smartphone.svg -fuzz 50% -transparent white   smartphone.png
convert smile-plus.svg -fuzz 50% -transparent white   smile-plus.png
convert smile.svg -fuzz 50% -transparent white   smile.png
convert snowflake.svg -fuzz 50% -transparent white   snowflake.png
convert sofa.svg -fuzz 50% -transparent white   sofa.png
convert sort-asc.svg -fuzz 50% -transparent white   sort-asc.png
convert sort-desc.svg -fuzz 50% -transparent white   sort-desc.png
convert speaker.svg -fuzz 50% -transparent white   speaker.png
convert spline.svg -fuzz 50% -transparent white   spline.png
convert sprout.svg -fuzz 50% -transparent white   sprout.png
convert square.svg -fuzz 50% -transparent white   square.png
convert star-half.svg -fuzz 50% -transparent white   star-half.png
convert star-off.svg -fuzz 50% -transparent white   star-off.png
convert star.svg -fuzz 50% -transparent white   star.png
convert stethoscope.svg -fuzz 50% -transparent white   stethoscope.png
convert sticker.svg -fuzz 50% -transparent white   sticker.png
convert sticky-note.svg -fuzz 50% -transparent white   sticky-note.png
convert stop-circle.svg -fuzz 50% -transparent white   stop-circle.png
convert stretch-horizontal.svg -fuzz 50% -transparent white   stretch-horizontal.png
convert stretch-vertical.svg -fuzz 50% -transparent white   stretch-vertical.png
convert strikethrough.svg -fuzz 50% -transparent white   strikethrough.png
convert subscript.svg -fuzz 50% -transparent white   subscript.png
convert sun-dim.svg -fuzz 50% -transparent white   sun-dim.png
convert sun-medium.svg -fuzz 50% -transparent white   sun-medium.png
convert sun-moon.svg -fuzz 50% -transparent white   sun-moon.png
convert sun-snow.svg -fuzz 50% -transparent white   sun-snow.png
convert sun.svg -fuzz 50% -transparent white   sun.png
convert sunrise.svg -fuzz 50% -transparent white   sunrise.png
convert sunset.svg -fuzz 50% -transparent white   sunset.png
convert superscript.svg -fuzz 50% -transparent white   superscript.png
convert swiss-franc.svg -fuzz 50% -transparent white   swiss-franc.png
convert switch-camera.svg -fuzz 50% -transparent white   switch-camera.png
convert sword.svg -fuzz 50% -transparent white   sword.png
convert swords.svg -fuzz 50% -transparent white   swords.png
convert syringe.svg -fuzz 50% -transparent white   syringe.png
convert table-2.svg -fuzz 50% -transparent white   table-2.png
convert table.svg -fuzz 50% -transparent white   table.png
convert tablet.svg -fuzz 50% -transparent white   tablet.png
convert tag.svg -fuzz 50% -transparent white   tag.png
convert tags.svg -fuzz 50% -transparent white   tags.png
convert target.svg -fuzz 50% -transparent white   target.png
convert tent.svg -fuzz 50% -transparent white   tent.png
convert terminal-square.svg -fuzz 50% -transparent white   terminal-square.png
convert terminal.svg -fuzz 50% -transparent white   terminal.png
convert text-cursor-input.svg -fuzz 50% -transparent white   text-cursor-input.png
convert text-cursor.svg -fuzz 50% -transparent white   text-cursor.png
convert thermometer-snowflake.svg -fuzz 50% -transparent white   thermometer-snowflake.png
convert thermometer-sun.svg -fuzz 50% -transparent white   thermometer-sun.png
convert thermometer.svg -fuzz 50% -transparent white   thermometer.png
convert thumbs-down.svg -fuzz 50% -transparent white   thumbs-down.png
convert thumbs-up.svg -fuzz 50% -transparent white   thumbs-up.png
convert ticket.svg -fuzz 50% -transparent white   ticket.png
convert timer-off.svg -fuzz 50% -transparent white   timer-off.png
convert timer-reset.svg -fuzz 50% -transparent white   timer-reset.png
convert timer.svg -fuzz 50% -transparent white   timer.png
convert toggle-left.svg -fuzz 50% -transparent white   toggle-left.png
convert toggle-right.svg -fuzz 50% -transparent white   toggle-right.png
convert tornado.svg -fuzz 50% -transparent white   tornado.png
convert toy-brick.svg -fuzz 50% -transparent white   toy-brick.png
convert train.svg -fuzz 50% -transparent white   train.png
convert trash-2.svg -fuzz 50% -transparent white   trash-2.png
convert trash.svg -fuzz 50% -transparent white   trash.png
convert tree-deciduous.svg -fuzz 50% -transparent white   tree-deciduous.png
convert tree-pine.svg -fuzz 50% -transparent white   tree-pine.png
convert trees.svg -fuzz 50% -transparent white   trees.png
convert trello.svg -fuzz 50% -transparent white   trello.png
convert trending-down.svg -fuzz 50% -transparent white   trending-down.png
convert trending-up.svg -fuzz 50% -transparent white   trending-up.png
convert triangle.svg -fuzz 50% -transparent white   triangle.png
convert trophy.svg -fuzz 50% -transparent white   trophy.png
convert truck.svg -fuzz 50% -transparent white   truck.png
convert tv-2.svg -fuzz 50% -transparent white   tv-2.png
convert tv.svg -fuzz 50% -transparent white   tv.png
convert twitch.svg -fuzz 50% -transparent white   twitch.png
convert twitter.svg -fuzz 50% -transparent white   twitter.png
convert type.svg -fuzz 50% -transparent white   type.png
convert umbrella.svg -fuzz 50% -transparent white   umbrella.png
convert underline.svg -fuzz 50% -transparent white   underline.png
convert undo-2.svg -fuzz 50% -transparent white   undo-2.png
convert undo.svg -fuzz 50% -transparent white   undo.png
convert unlink-2.svg -fuzz 50% -transparent white   unlink-2.png
convert unlink.svg -fuzz 50% -transparent white   unlink.png
convert unlock.svg -fuzz 50% -transparent white   unlock.png
convert upload-cloud.svg -fuzz 50% -transparent white   upload-cloud.png
convert upload.svg -fuzz 50% -transparent white   upload.png
convert usb.svg -fuzz 50% -transparent white   usb.png
convert user-check.svg -fuzz 50% -transparent white   user-check.png
convert user-cog.svg -fuzz 50% -transparent white   user-cog.png
convert user-minus.svg -fuzz 50% -transparent white   user-minus.png
convert user-plus.svg -fuzz 50% -transparent white   user-plus.png
convert user-x.svg -fuzz 50% -transparent white   user-x.png
convert user.svg -fuzz 50% -transparent white   user.png
convert users.svg -fuzz 50% -transparent white   users.png
convert utensils-crossed.svg -fuzz 50% -transparent white   utensils-crossed.png
convert utensils.svg -fuzz 50% -transparent white   utensils.png
convert vegan.svg -fuzz 50% -transparent white   vegan.png
convert venetian-mask.svg -fuzz 50% -transparent white   venetian-mask.png
convert verified.svg -fuzz 50% -transparent white   verified.png
convert vibrate-off.svg -fuzz 50% -transparent white   vibrate-off.png
convert vibrate.svg -fuzz 50% -transparent white   vibrate.png
convert video-off.svg -fuzz 50% -transparent white   video-off.png
convert video.svg -fuzz 50% -transparent white   video.png
convert view.svg -fuzz 50% -transparent white   view.png
convert voicemail.svg -fuzz 50% -transparent white   voicemail.png
convert volume-1.svg -fuzz 50% -transparent white   volume-1.png
convert volume-2.svg -fuzz 50% -transparent white   volume-2.png
convert volume-x.svg -fuzz 50% -transparent white   volume-x.png
convert volume.svg -fuzz 50% -transparent white   volume.png
convert wallet.svg -fuzz 50% -transparent white   wallet.png
convert wand-2.svg -fuzz 50% -transparent white   wand-2.png
convert wand.svg -fuzz 50% -transparent white   wand.png
convert watch.svg -fuzz 50% -transparent white   watch.png
convert waves.svg -fuzz 50% -transparent white   waves.png
convert webcam.svg -fuzz 50% -transparent white   webcam.png
convert webhook.svg -fuzz 50% -transparent white   webhook.png
convert wheat-off.svg -fuzz 50% -transparent white   wheat-off.png
convert wheat.svg -fuzz 50% -transparent white   wheat.png
convert wifi-off.svg -fuzz 50% -transparent white   wifi-off.png
convert wifi.svg -fuzz 50% -transparent white   wifi.png
convert wind.svg -fuzz 50% -transparent white   wind.png
convert wine-off.svg -fuzz 50% -transparent white   wine-off.png
convert wine.svg -fuzz 50% -transparent white   wine.png
convert wrap-text.svg -fuzz 50% -transparent white   wrap-text.png
convert wrench.svg -fuzz 50% -transparent white   wrench.png
convert x-circle.svg -fuzz 50% -transparent white   x-circle.png
convert x-octagon.svg -fuzz 50% -transparent white   x-octagon.png
convert x-square.svg -fuzz 50% -transparent white   x-square.png
convert x.svg -fuzz 50% -transparent white   x.png
convert youtube.svg -fuzz 50% -transparent white   youtube.png
convert zap-off.svg -fuzz 50% -transparent white   zap-off.png
convert zap.svg -fuzz 50% -transparent white   zap.png
convert zoom-in.svg -fuzz 50% -transparent white   zoom-in.png
convert zoom-out.svg -fuzz 50% -transparent white   zoom-out.png
