icon.type_geo_project.mining=/geo/icons/mining.png
icon.type_geo_project.borehole_drilling=/geo/icons/drilling-rig.png
icon.type_geo_project.oil_gas_production=/geo/icons/drilling-rig.png
icon.type_geo_project.oil_gas_exploration=/geo/icons/drilling-rig.png

