/*
* Copyright (c) 2008-2018 Geode Systems LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*     http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package org.ramadda.util.grid;


import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.*;

import java.io.File;

import java.util.List;



/**
 * !!!!!!!!NOTE!!!!!!!
 * This file is copied from the UNAVCO SVN tree (I know I shouldn't do this
 * but I couldn't deal with yet another library from somewhere else).
 * SO: DO NOT EDIT THIS FILE HERE OR IF YOU DO MAKE SURE ITS CHECKED INTO
 * THE UNAVCO TREE
 *
 * @param <T>
 */
public class ObjectGrid<T> extends Grid {

    /** An extra 2d array of counts */
    private T[][] objectGrid;


    /**
     * ctor
     *
     * @param width number of columns
     * @param height number of rows
     * @param north northern bounds
     * @param west west bounds
     * @param south southern bounds
     * @param east east bounds
     */
    public ObjectGrid(int width, int height, double north, double west,
                      double south, double east) {
        super(width, height, north, west, south, east);
    }



    /**
     * create if needed and return the grid
     *
     * @return the grid
     */
    public T[][] getGrid() {
        if (objectGrid == null) {
            objectGrid = (T[][]) new Object[getHeight()][getWidth()];
        }

        return objectGrid;
    }


    /**
     * _more_
     *
     * @param lat _more_
     * @param lon _more_
     *
     * @return _more_
     */
    public T getValue(double lat, double lon) {
        int yIndex = getLatitudeIndex(lat);
        int xIndex = getLongitudeIndex(lon);

        return getGrid()[yIndex][xIndex];
    }

    /**
     * _more_
     *
     * @param yIndex _more_
     * @param xIndex _more_
     *
     * @return _more_
     */
    public T getValueFromIndex(int yIndex, int xIndex) {
        return getGrid()[yIndex][xIndex];
    }


    /**
     * _more_
     *
     * @param lat _more_
     * @param lon _more_
     * @param value _more_
     */
    public void setValue(double lat, double lon, T value) {
        setValueByIndex(getLatitudeIndex(lat), getLongitudeIndex(lon), value);
    }

    /**
     * _more_
     *
     * @param yIndex _more_
     * @param xIndex _more_
     * @param value _more_
     */
    public void setValueByIndex(int yIndex, int xIndex, T value) {
        getGrid()[yIndex][xIndex] = value;
    }



    /**
     * _more_
     *
     * @param args _more_
     */
    public static void main(String[] args) {}

}
